// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_sessions

import (
	"database/sql"
	"time"
)

type Session struct {
	SessionID []byte
	UserID    []byte
	Active    sql.NullBool
	CreatedAt sql.NullTime
	ExpiresAt time.Time
}

type User struct {
	UserID       []byte
	Email        string
	PasswordHash []byte
	FirstName    string
	LastName     string
	Dob          string
	Avatar       sql.NullString
	Nickname     sql.NullString
	AboutMe      sql.NullString
	IsPublic     bool
	CreatedAt    sql.NullTime
}
