// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db_sessions

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (session_id, user_id, active, expires_at) VALUES (?, ?, 1, ?) RETURNING session_id, user_id, active, created_at, expires_at
`

type CreateSessionParams struct {
	SessionID []byte
	UserID    []byte
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.SessionID, arg.UserID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.Active,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getSessionByUserID = `-- name: GetSessionByUserID :one
SELECT session_id, user_id, active, created_at, expires_at FROM sessions WHERE user_id = ?
`

func (q *Queries) GetSessionByUserID(ctx context.Context, userID []byte) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByUserID, userID)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.Active,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
