// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package db_chat

import (
	"context"
	"database/sql"
)

const addRoomParticipant = `-- name: AddRoomParticipant :exec
INSERT INTO chat_participants (room_id, user_id) VALUES (?, ?)
`

type AddRoomParticipantParams struct {
	RoomID []byte
	UserID []byte
}

func (q *Queries) AddRoomParticipant(ctx context.Context, arg AddRoomParticipantParams) error {
	_, err := q.db.ExecContext(ctx, addRoomParticipant, arg.RoomID, arg.UserID)
	return err
}

const checkUserIsParticipant = `-- name: CheckUserIsParticipant :one
SELECT COUNT(*) FROM chat_participants WHERE user_id = ? AND room_id = ?
`

type CheckUserIsParticipantParams struct {
	UserID []byte
	RoomID []byte
}

func (q *Queries) CheckUserIsParticipant(ctx context.Context, arg CheckUserIsParticipantParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkUserIsParticipant, arg.UserID, arg.RoomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMessage = `-- name: CreateMessage :exec
INSERT INTO chat_messages (message_id, content, sender_id, target_id) VALUES (?, ?, ?, ?)
`

type CreateMessageParams struct {
	MessageID []byte
	Content   string
	SenderID  []byte
	TargetID  []byte
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.ExecContext(ctx, createMessage,
		arg.MessageID,
		arg.Content,
		arg.SenderID,
		arg.TargetID,
	)
	return err
}

const createRoom = `-- name: CreateRoom :exec
INSERT INTO chat_rooms (room_id, name, group_id) VALUES (?, ?, ?)
`

type CreateRoomParams struct {
	RoomID  []byte
	Name    sql.NullString
	GroupID []byte
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) error {
	_, err := q.db.ExecContext(ctx, createRoom, arg.RoomID, arg.Name, arg.GroupID)
	return err
}

const findRoomBetweenUsers = `-- name: FindRoomBetweenUsers :one
SELECT cr.room_id
FROM chat_rooms cr
         INNER JOIN chat_participants cp1
                    ON cr.room_id = cp1.room_id
                        AND cp1.user_id = ?
         INNER JOIN chat_participants cp2
                    ON cr.room_id = cp2.room_id
                        AND cp2.user_id = ?
WHERE cr.group_id != null
  AND cp1.user_id != cp2.user_id  -- Ensure different users
LIMIT 1
`

type FindRoomBetweenUsersParams struct {
	UserID   []byte
	UserID_2 []byte
}

func (q *Queries) FindRoomBetweenUsers(ctx context.Context, arg FindRoomBetweenUsersParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, findRoomBetweenUsers, arg.UserID, arg.UserID_2)
	var room_id []byte
	err := row.Scan(&room_id)
	return room_id, err
}

const getRoomIdByGroupId = `-- name: GetRoomIdByGroupId :one
SELECT cr.room_id as room_id FROM chat_rooms cr WHERE cr.group_id = ?
`

func (q *Queries) GetRoomIdByGroupId(ctx context.Context, groupID []byte) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getRoomIdByGroupId, groupID)
	var room_id []byte
	err := row.Scan(&room_id)
	return room_id, err
}

const getRoomMessages = `-- name: GetRoomMessages :many
SELECT
    cm.message_id,
    cm.content,
    cm.sender_id,
    cm.target_id,
    cm.created_at,
    u.first_name AS sender_first_name,
    u.last_name AS sender_last_name,
    u.avatar AS sender_avatar
FROM chat_messages cm
JOIN users u ON cm.sender_id = u.user_id
WHERE cm.target_id = ?
  AND (? IS NULL OR cm.created_at <= ?)
  AND (? IS NULL OR cm.message_id != ?)
ORDER BY cm.created_at DESC, cm.message_id DESC
    LIMIT ?
`

type GetRoomMessagesParams struct {
	TargetID  []byte
	Column2   interface{}
	CreatedAt sql.NullTime
	Column4   interface{}
	MessageID []byte
	Limit     int64
}

type GetRoomMessagesRow struct {
	MessageID       []byte
	Content         string
	SenderID        []byte
	TargetID        []byte
	CreatedAt       sql.NullTime
	SenderFirstName string
	SenderLastName  string
	SenderAvatar    sql.NullString
}

func (q *Queries) GetRoomMessages(ctx context.Context, arg GetRoomMessagesParams) ([]GetRoomMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, getRoomMessages,
		arg.TargetID,
		arg.Column2,
		arg.CreatedAt,
		arg.Column4,
		arg.MessageID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoomMessagesRow
	for rows.Next() {
		var i GetRoomMessagesRow
		if err := rows.Scan(
			&i.MessageID,
			&i.Content,
			&i.SenderID,
			&i.TargetID,
			&i.CreatedAt,
			&i.SenderFirstName,
			&i.SenderLastName,
			&i.SenderAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomMessagesCount = `-- name: GetRoomMessagesCount :one
SELECT COUNT(*) FROM chat_messages WHERE target_id = ?
`

func (q *Queries) GetRoomMessagesCount(ctx context.Context, targetID []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, getRoomMessagesCount, targetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRoomParticipants = `-- name: GetRoomParticipants :many
SELECT user_id FROM chat_participants WHERE room_id = ?
`

func (q *Queries) GetRoomParticipants(ctx context.Context, roomID []byte) ([][]byte, error) {
	rows, err := q.db.QueryContext(ctx, getRoomParticipants, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var user_id []byte
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBasicInfo = `-- name: GetUserBasicInfo :one
SELECT first_name, last_name, avatar FROM users WHERE user_id = ?
`

type GetUserBasicInfoRow struct {
	FirstName string
	LastName  string
	Avatar    sql.NullString
}

func (q *Queries) GetUserBasicInfo(ctx context.Context, userID []byte) (GetUserBasicInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getUserBasicInfo, userID)
	var i GetUserBasicInfoRow
	err := row.Scan(&i.FirstName, &i.LastName, &i.Avatar)
	return i, err
}

const getUserChatList = `-- name: GetUserChatList :many
SELECT
    cr.room_id,
    cr.name AS room_name,
    cr.group_id,
    cr.created_at AS room_created_at,

    lm.message_id AS last_message_id,
    lm.content AS last_message_content,
    lm.created_at AS last_message_time,
    lm.sender_id AS last_message_sender_id,

    CAST(COALESCE(
            (SELECT COUNT(*)
             FROM chat_messages cm
             WHERE cm.target_id = cr.room_id
               AND cm.sender_id != ?
           AND cm.created_at >= COALESCE(cp.last_read_at, cp.joined_at, '1970-01-01')
        ), 0
    ) AS INTEGER) AS unread_count,

    cp.last_read_at,
    cp.joined_at

FROM chat_rooms cr

         INNER JOIN chat_participants cp
                    ON cr.room_id = cp.room_id
                        AND cp.user_id = ?

         LEFT JOIN (
    SELECT cm1.message_id, cm1.content, cm1.sender_id, cm1.target_id, cm1.created_at
    FROM chat_messages cm1
             INNER JOIN (
        SELECT target_id, MAX(created_at) AS max_time
        FROM chat_messages
        GROUP BY target_id
    ) cm2 ON cm1.target_id = cm2.target_id
        AND cm1.created_at = cm2.max_time
) lm ON cr.room_id = lm.target_id

ORDER BY COALESCE(lm.created_at, cr.created_at) DESC
`

type GetUserChatListParams struct {
	SenderID []byte
	UserID   []byte
}

type GetUserChatListRow struct {
	RoomID              []byte
	RoomName            sql.NullString
	GroupID             []byte
	RoomCreatedAt       sql.NullTime
	LastMessageID       []byte
	LastMessageContent  string
	LastMessageTime     sql.NullTime
	LastMessageSenderID []byte
	UnreadCount         int64
	LastReadAt          sql.NullTime
	JoinedAt            sql.NullTime
}

func (q *Queries) GetUserChatList(ctx context.Context, arg GetUserChatListParams) ([]GetUserChatListRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserChatList, arg.SenderID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserChatListRow
	for rows.Next() {
		var i GetUserChatListRow
		if err := rows.Scan(
			&i.RoomID,
			&i.RoomName,
			&i.GroupID,
			&i.RoomCreatedAt,
			&i.LastMessageID,
			&i.LastMessageContent,
			&i.LastMessageTime,
			&i.LastMessageSenderID,
			&i.UnreadCount,
			&i.LastReadAt,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRoomMessagesAsRead = `-- name: MarkRoomMessagesAsRead :exec
UPDATE chat_participants SET last_read_at = CURRENT_TIMESTAMP WHERE user_id = ? AND room_id = ?
`

type MarkRoomMessagesAsReadParams struct {
	UserID []byte
	RoomID []byte
}

func (q *Queries) MarkRoomMessagesAsRead(ctx context.Context, arg MarkRoomMessagesAsReadParams) error {
	_, err := q.db.ExecContext(ctx, markRoomMessagesAsRead, arg.UserID, arg.RoomID)
	return err
}

const removeRoomParticipant = `-- name: RemoveRoomParticipant :exec
DELETE FROM chat_participants WHERE user_id = ? AND room_id = ?
`

type RemoveRoomParticipantParams struct {
	UserID []byte
	RoomID []byte
}

func (q *Queries) RemoveRoomParticipant(ctx context.Context, arg RemoveRoomParticipantParams) error {
	_, err := q.db.ExecContext(ctx, removeRoomParticipant, arg.UserID, arg.RoomID)
	return err
}
