// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package db_chat

import (
	"context"
	"database/sql"
)

const addRoomParticipant = `-- name: AddRoomParticipant :exec
INSERT INTO chat_participants (room_id, user_id) VALUES (?, ?)
`

type AddRoomParticipantParams struct {
	RoomID []byte
	UserID []byte
}

func (q *Queries) AddRoomParticipant(ctx context.Context, arg AddRoomParticipantParams) error {
	_, err := q.db.ExecContext(ctx, addRoomParticipant, arg.RoomID, arg.UserID)
	return err
}

const checkUserIsParticipant = `-- name: CheckUserIsParticipant :one
SELECT COUNT(*) FROM chat_participants WHERE user_id = ? AND room_id = ?
`

type CheckUserIsParticipantParams struct {
	UserID []byte
	RoomID []byte
}

func (q *Queries) CheckUserIsParticipant(ctx context.Context, arg CheckUserIsParticipantParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkUserIsParticipant, arg.UserID, arg.RoomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMessage = `-- name: CreateMessage :exec
INSERT INTO chat_messages (message_id, content, sender_id, target_id) VALUES (?, ?, ?, ?)
`

type CreateMessageParams struct {
	MessageID []byte
	Content   string
	SenderID  []byte
	TargetID  []byte
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.ExecContext(ctx, createMessage,
		arg.MessageID,
		arg.Content,
		arg.SenderID,
		arg.TargetID,
	)
	return err
}

const createRoom = `-- name: CreateRoom :exec
INSERT INTO chat_rooms (room_id, name, is_group) VALUES (?, ?, ?)
`

type CreateRoomParams struct {
	RoomID  []byte
	Name    sql.NullString
	IsGroup int64
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) error {
	_, err := q.db.ExecContext(ctx, createRoom, arg.RoomID, arg.Name, arg.IsGroup)
	return err
}

const getRoomMessages = `-- name: GetRoomMessages :many
SELECT
    cm.message_id,
    cm.content,
    cm.sender_id,
    cm.target_id,
    cm.created_at
FROM chat_messages cm
WHERE cm.target_id = ?
  AND (? IS NULL OR cm.created_at < ?)  -- Cursor pagination
ORDER BY cm.created_at DESC
    LIMIT ?
`

type GetRoomMessagesParams struct {
	TargetID  []byte
	Column2   interface{}
	CreatedAt sql.NullTime
	Limit     int64
}

func (q *Queries) GetRoomMessages(ctx context.Context, arg GetRoomMessagesParams) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, getRoomMessages,
		arg.TargetID,
		arg.Column2,
		arg.CreatedAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.MessageID,
			&i.Content,
			&i.SenderID,
			&i.TargetID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomMessagesCount = `-- name: GetRoomMessagesCount :one
SELECT COUNT(*) FROM chat_messages WHERE target_id = ?
`

func (q *Queries) GetRoomMessagesCount(ctx context.Context, targetID []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, getRoomMessagesCount, targetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserChatList = `-- name: GetUserChatList :many
SELECT
    cr.room_id,
    cr.name AS room_name,
    cr.is_group,
    cr.created_at AS room_created_at,

    lm.message_id AS last_message_id,
    lm.content AS last_message_content,
    lm.created_at AS last_message_time,
    lm.sender_id AS last_message_sender_id,

    CASE WHEN cr.is_group = 0 THEN other_user.user_id ELSE NULL END AS other_user_id,

    CAST(COALESCE(
            (SELECT COUNT(*)
             FROM chat_messages cm
             WHERE cm.target_id = cr.room_id
               AND cm.sender_id != ?
           AND cm.created_at > COALESCE(cp.last_read_at, cp.joined_at, '1970-01-01')
        ), 0
    ) AS INTEGER) AS unread_count,

    cp.last_read_at,
    cp.joined_at

FROM chat_rooms cr

         INNER JOIN chat_participants cp
                    ON cr.room_id = cp.room_id
                        AND cp.user_id = ?

         LEFT JOIN (
    SELECT cm1.message_id, cm1.content, cm1.sender_id, cm1.target_id, cm1.created_at
    FROM chat_messages cm1
             INNER JOIN (
        SELECT target_id, MAX(created_at) AS max_time
        FROM chat_messages
        GROUP BY target_id
    ) cm2 ON cm1.target_id = cm2.target_id
        AND cm1.created_at = cm2.max_time
) lm ON cr.room_id = lm.target_id

         LEFT JOIN chat_participants other_cp
                   ON cr.room_id = other_cp.room_id
                       AND other_cp.user_id != ?
    AND cr.is_group = 0
LEFT JOIN users other_user ON other_cp.user_id = other_user.user_id

ORDER BY COALESCE(lm.created_at, cr.created_at) DESC
`

type GetUserChatListParams struct {
	SenderID []byte
	UserID   []byte
	UserID_2 []byte
}

type GetUserChatListRow struct {
	RoomID              []byte
	RoomName            sql.NullString
	IsGroup             int64
	RoomCreatedAt       sql.NullTime
	LastMessageID       []byte
	LastMessageContent  string
	LastMessageTime     sql.NullTime
	LastMessageSenderID []byte
	OtherUserID         interface{}
	UnreadCount         int64
	LastReadAt          sql.NullTime
	JoinedAt            sql.NullTime
}

func (q *Queries) GetUserChatList(ctx context.Context, arg GetUserChatListParams) ([]GetUserChatListRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserChatList, arg.SenderID, arg.UserID, arg.UserID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserChatListRow
	for rows.Next() {
		var i GetUserChatListRow
		if err := rows.Scan(
			&i.RoomID,
			&i.RoomName,
			&i.IsGroup,
			&i.RoomCreatedAt,
			&i.LastMessageID,
			&i.LastMessageContent,
			&i.LastMessageTime,
			&i.LastMessageSenderID,
			&i.OtherUserID,
			&i.UnreadCount,
			&i.LastReadAt,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRoomMessagesAsRead = `-- name: MarkRoomMessagesAsRead :exec
UPDATE chat_participants SET last_read_at = ? WHERE user_id = ? AND room_id = ?
`

type MarkRoomMessagesAsReadParams struct {
	LastReadAt sql.NullTime
	UserID     []byte
	RoomID     []byte
}

func (q *Queries) MarkRoomMessagesAsRead(ctx context.Context, arg MarkRoomMessagesAsReadParams) error {
	_, err := q.db.ExecContext(ctx, markRoomMessagesAsRead, arg.LastReadAt, arg.UserID, arg.RoomID)
	return err
}

const removeRoomParticipant = `-- name: RemoveRoomParticipant :exec
DELETE FROM chat_participants WHERE user_id = ? AND room_id = ?
`

type RemoveRoomParticipantParams struct {
	UserID []byte
	RoomID []byte
}

func (q *Queries) RemoveRoomParticipant(ctx context.Context, arg RemoveRoomParticipantParams) error {
	_, err := q.db.ExecContext(ctx, removeRoomParticipant, arg.UserID, arg.RoomID)
	return err
}
