// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_chat

import (
	"database/sql"
)

type ChatMessage struct {
	MessageID []byte
	Content   string
	SenderID  []byte
	TargetID  []byte
	CreatedAt sql.NullTime
}

type ChatParticipant struct {
	ID         int64
	RoomID     []byte
	UserID     []byte
	JoinedAt   sql.NullTime
	LastReadAt sql.NullTime
}

type ChatRoom struct {
	RoomID    []byte
	Name      sql.NullString
	GroupID   []byte
	CreatedAt sql.NullTime
}

type User struct {
	UserID       []byte
	Email        string
	PasswordHash []byte
	FirstName    string
	LastName     string
	Dob          string
	Avatar       sql.NullString
	Nickname     sql.NullString
	AboutMe      sql.NullString
	IsPublic     bool
	CreatedAt    sql.NullTime
}
