// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: image.sql

package db_image

import (
	"context"
	"strings"
)

const assignImage = `-- name: AssignImage :exec
UPDATE images SET expires_at = NULL WHERE image_id = ?
`

func (q *Queries) AssignImage(ctx context.Context, imageID string) error {
	_, err := q.db.ExecContext(ctx, assignImage, imageID)
	return err
}

const createImage = `-- name: CreateImage :exec
INSERT INTO images (image_id, poster_id, image_path, file_name, created_at, expires_at)
VALUES(?, ?, ?, ?, CAST(? AS TEXT), CAST(? AS TEXT))
`

type CreateImageParams struct {
	ImageID   string
	PosterID  []byte
	ImagePath string
	FileName  string
	Column5   string
	Column6   string
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) error {
	_, err := q.db.ExecContext(ctx, createImage,
		arg.ImageID,
		arg.PosterID,
		arg.ImagePath,
		arg.FileName,
		arg.Column5,
		arg.Column6,
	)
	return err
}

const deleteImages = `-- name: DeleteImages :exec
DELETE FROM images WHERE image_id IN (/*SLICE:image_id*/?)
`

func (q *Queries) DeleteImages(ctx context.Context, imageID []string) error {
	query := deleteImages
	var queryParams []interface{}
	if len(imageID) > 0 {
		for _, v := range imageID {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:image_id*/?", strings.Repeat(",?", len(imageID))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:image_id*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const getImageById = `-- name: GetImageById :one
SELECT image_id, poster_id, image_path, file_name, created_at, expires_at FROM images WHERE image_id = ? LIMIT 1
`

func (q *Queries) GetImageById(ctx context.Context, imageID string) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImageById, imageID)
	var i Image
	err := row.Scan(
		&i.ImageID,
		&i.PosterID,
		&i.ImagePath,
		&i.FileName,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getNotSetImages = `-- name: GetNotSetImages :many
SELECT image_id, poster_id, image_path, file_name, created_at, expires_at FROM images WHERE expires_at IS NOT NULL AND expires_at != ''
`

func (q *Queries) GetNotSetImages(ctx context.Context) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, getNotSetImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ImageID,
			&i.PosterID,
			&i.ImagePath,
			&i.FileName,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setImageExpiry = `-- name: SetImageExpiry :exec
UPDATE images SET expires_at = CAST(? AS TEXT) WHERE image_id = ?
`

type SetImageExpiryParams struct {
	Column1 string
	ImageID string
}

func (q *Queries) SetImageExpiry(ctx context.Context, arg SetImageExpiryParams) error {
	_, err := q.db.ExecContext(ctx, setImageExpiry, arg.Column1, arg.ImageID)
	return err
}
