// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: image.sql

package db_image

import (
	"context"
	"database/sql"
	"strings"
)

const createImage = `-- name: CreateImage :exec
INSERT INTO images (image_id, poster_id, image_path, created_at, expires_at)
VALUES(?, ?, ?, ?, ?)
`

type CreateImageParams struct {
	ImageID   string
	PosterID  []byte
	ImagePath string
	CreatedAt sql.NullTime
	ExpiresAt sql.NullTime
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) error {
	_, err := q.db.ExecContext(ctx, createImage,
		arg.ImageID,
		arg.PosterID,
		arg.ImagePath,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteImages = `-- name: DeleteImages :exec
DELETE FROM images WHERE image_id IN (/*SLICE:image_id*/?)
`

func (q *Queries) DeleteImages(ctx context.Context, imageID []string) error {
	query := deleteImages
	var queryParams []interface{}
	if len(imageID) > 0 {
		for _, v := range imageID {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:image_id*/?", strings.Repeat(",?", len(imageID))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:image_id*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const getNotSetImages = `-- name: GetNotSetImages :many
SELECT image_id, poster_id, image_path, created_at, expires_at FROM images WHERE expires_at IS NOT NULL
`

func (q *Queries) GetNotSetImages(ctx context.Context) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, getNotSetImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ImageID,
			&i.PosterID,
			&i.ImagePath,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const imageState = `-- name: ImageState :exec
UPDATE images SET expires_at = ? WHERE image_id = ?
`

type ImageStateParams struct {
	ExpiresAt sql.NullTime
	ImageID   string
}

func (q *Queries) ImageState(ctx context.Context, arg ImageStateParams) error {
	_, err := q.db.ExecContext(ctx, imageState, arg.ExpiresAt, arg.ImageID)
	return err
}
