// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_image

import (
	"database/sql"
)

type Image struct {
	ImageID   string
	PosterID  []byte
	ImagePath string
	FileName  string
	CreatedAt sql.NullTime
	ExpiresAt sql.NullTime
}

type User struct {
	UserID       []byte
	Email        string
	PasswordHash []byte
	FirstName    string
	LastName     string
	Dob          string
	Avatar       sql.NullString
	Nickname     sql.NullString
	AboutMe      sql.NullString
	IsPublic     bool
	CreatedAt    sql.NullTime
}
