// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_posts

import (
	"database/sql"
	"time"
)

type Comment struct {
	CommentID       []byte
	PostID          []byte
	AuthorID        []byte
	ParentCommentID []byte
	Content         string
	ImageID         sql.NullString
	CreatedAt       sql.NullTime
}

type Follower struct {
	FollowerID []byte
	FolloweeID []byte
	Status     string
	CreatedAt  sql.NullTime
}

type Group struct {
	GroupID     []byte
	GroupName   string
	Description string
	Image       sql.NullString
	CreatorID   []byte
	CreatedAt   time.Time
}

type Image struct {
	ImageID   string
	PosterID  []byte
	ImagePath string
	FileName  string
	CreatedAt sql.NullTime
	ExpiresAt sql.NullTime
}

type Post struct {
	PostID     []byte
	AuthorID   []byte
	Content    string
	ImageID    sql.NullString
	Visibility string
	CreatedAt  sql.NullTime
	GroupID    []byte
}

type Reaction struct {
	ReactionID []byte
	AuthorID   []byte
	TargetType string
	TargetID   []byte
	ReactedAt  sql.NullTime
}

type User struct {
	UserID       []byte
	Email        string
	PasswordHash []byte
	FirstName    string
	LastName     string
	Dob          string
	Avatar       sql.NullString
	Nickname     sql.NullString
	AboutMe      sql.NullString
	IsPublic     bool
	CreatedAt    sql.NullTime
}

type ViewingPermission struct {
	PostID    []byte
	UserID    []byte
	CreatedAt sql.NullTime
}
