// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package db_posts

import (
	"context"
	"database/sql"
)

const addPrivatePostViewingPermission = `-- name: AddPrivatePostViewingPermission :execrows
INSERT INTO viewing_permissions (user_id, post_id)
SELECT ?, ?
    WHERE EXISTS (
    SELECT 1 FROM posts p
    WHERE p.post_id = ?
      AND p.visibility = 'private'
      AND EXISTS (
          SELECT 1 FROM followers f
          WHERE f.follower_id = ?
            AND f.followee_id = p.author_id
      )
)
`

type AddPrivatePostViewingPermissionParams struct {
	UserID     []byte
	PostID     string
	PostID_2   []byte
	FollowerID []byte
}

func (q *Queries) AddPrivatePostViewingPermission(ctx context.Context, arg AddPrivatePostViewingPermissionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addPrivatePostViewingPermission,
		arg.UserID,
		arg.PostID,
		arg.PostID_2,
		arg.FollowerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const checkPrivatePostUserPermit = `-- name: CheckPrivatePostUserPermit :one
SELECT post_id, user_id, created_at FROM viewing_permissions WHERE user_id = ? AND post_id = ?
`

type CheckPrivatePostUserPermitParams struct {
	UserID []byte
	PostID string
}

func (q *Queries) CheckPrivatePostUserPermit(ctx context.Context, arg CheckPrivatePostUserPermitParams) (ViewingPermission, error) {
	row := q.db.QueryRowContext(ctx, checkPrivatePostUserPermit, arg.UserID, arg.PostID)
	var i ViewingPermission
	err := row.Scan(&i.PostID, &i.UserID, &i.CreatedAt)
	return i, err
}

const createComment = `-- name: CreateComment :execrows
INSERT INTO comments (comment_id, post_id, user_id, content, parent_comment_id, image_id)
SELECT ?, ?, ?, ?, ?, ?
    WHERE EXISTS (
    SELECT 1 FROM posts p
    WHERE p.post_id = ?
      AND (
          p.visibility = 'public'
          OR EXISTS (
              SELECT 1 FROM followers f
              WHERE f.follower_id = ?
                AND f.followee_id = p.author_id
          )
          OR EXISTS (
              SELECT 1 FROM viewing_permissions vp
              WHERE vp.user_id = ?
                AND vp.post_id = p.post_id
          )
      )
)
`

type CreateCommentParams struct {
	CommentID       string
	PostID          string
	UserID          []byte
	Content         string
	ParentCommentID sql.NullString
	ImageID         sql.NullString
	PostID_2        []byte
	FollowerID      []byte
	UserID_2        []byte
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createComment,
		arg.CommentID,
		arg.PostID,
		arg.UserID,
		arg.Content,
		arg.ParentCommentID,
		arg.ImageID,
		arg.PostID_2,
		arg.FollowerID,
		arg.UserID_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (post_id, author_id, content, visibility, image_id) VALUES (?, ?, ?, ?, ?) RETURNING post_id, author_id, content, image_id, visibility, created_at
`

type CreatePostParams struct {
	PostID     []byte
	AuthorID   []byte
	Content    string
	Visibility string
	ImageID    sql.NullString
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.PostID,
		arg.AuthorID,
		arg.Content,
		arg.Visibility,
		arg.ImageID,
	)
	var i Post
	err := row.Scan(
		&i.PostID,
		&i.AuthorID,
		&i.Content,
		&i.ImageID,
		&i.Visibility,
		&i.CreatedAt,
	)
	return i, err
}

const createReaction = `-- name: CreateReaction :execrows
INSERT INTO reactions (reaction_id, target_type, target_id, user_id, reaction_type)
SELECT ?, ?, ?, ?, ?
    WHERE EXISTS (
    SELECT 1 FROM posts p
    WHERE p.post_id = (
        CASE
            WHEN ? = 'post' THEN ?
            WHEN ? = 'comment' THEN (SELECT post_id FROM comments WHERE comment_id = ?)
        END
    )
    AND (
        p.visibility = 'public'
        OR EXISTS (
            SELECT 1 FROM followers f
            WHERE f.follower_id = ?
              AND f.followee_id = p.author_id
        )
        OR EXISTS (
            SELECT 1 FROM viewing_permissions vp
            WHERE vp.user_id = ?
              AND vp.post_id = p.post_id
        )
    )
)
`

type CreateReactionParams struct {
	ReactionID   string
	TargetType   string
	TargetID     string
	UserID       []byte
	ReactionType string
	Column6      interface{}
	PostID       []byte
	Column8      interface{}
	CommentID    string
	FollowerID   []byte
	UserID_2     []byte
}

func (q *Queries) CreateReaction(ctx context.Context, arg CreateReactionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createReaction,
		arg.ReactionID,
		arg.TargetType,
		arg.TargetID,
		arg.UserID,
		arg.ReactionType,
		arg.Column6,
		arg.PostID,
		arg.Column8,
		arg.CommentID,
		arg.FollowerID,
		arg.UserID_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE comment_id = ? AND user_id = ?
`

type DeleteCommentParams struct {
	CommentID string
	UserID    []byte
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) error {
	_, err := q.db.ExecContext(ctx, deleteComment, arg.CommentID, arg.UserID)
	return err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE post_id = ? and author_id = ?
`

type DeletePostParams struct {
	PostID   []byte
	AuthorID []byte
}

func (q *Queries) DeletePost(ctx context.Context, arg DeletePostParams) error {
	_, err := q.db.ExecContext(ctx, deletePost, arg.PostID, arg.AuthorID)
	return err
}

const deleteReaction = `-- name: DeleteReaction :exec
DELETE FROM reactions WHERE reaction_id = ? AND user_id = ?
`

type DeleteReactionParams struct {
	ReactionID string
	UserID     []byte
}

func (q *Queries) DeleteReaction(ctx context.Context, arg DeleteReactionParams) error {
	_, err := q.db.ExecContext(ctx, deleteReaction, arg.ReactionID, arg.UserID)
	return err
}

const editComment = `-- name: EditComment :exec
UPDATE comments SET content = ? WHERE comment_id = ? AND user_id = ?
`

type EditCommentParams struct {
	Content   string
	CommentID string
	UserID    []byte
}

func (q *Queries) EditComment(ctx context.Context, arg EditCommentParams) error {
	_, err := q.db.ExecContext(ctx, editComment, arg.Content, arg.CommentID, arg.UserID)
	return err
}

const editPostVisibility = `-- name: EditPostVisibility :exec
UPDATE posts SET visibility = ? WHERE post_id = ? and author_id = ?
`

type EditPostVisibilityParams struct {
	Visibility string
	PostID     []byte
	AuthorID   []byte
}

func (q *Queries) EditPostVisibility(ctx context.Context, arg EditPostVisibilityParams) error {
	_, err := q.db.ExecContext(ctx, editPostVisibility, arg.Visibility, arg.PostID, arg.AuthorID)
	return err
}

const getCommentReactions = `-- name: GetCommentReactions :many
SELECT reaction_id, user_id, target_type, target_id, reaction_type, reacted_at FROM reactions WHERE target_type = 'comment' AND target_id = ?
`

func (q *Queries) GetCommentReactions(ctx context.Context, targetID string) ([]Reaction, error) {
	rows, err := q.db.QueryContext(ctx, getCommentReactions, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reaction
	for rows.Next() {
		var i Reaction
		if err := rows.Scan(
			&i.ReactionID,
			&i.UserID,
			&i.TargetType,
			&i.TargetID,
			&i.ReactionType,
			&i.ReactedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostBasicInfo = `-- name: GetPostBasicInfo :one
SELECT post_id, author_id, visibility FROM posts WHERE post_id = ?
`

type GetPostBasicInfoRow struct {
	PostID     []byte
	AuthorID   []byte
	Visibility string
}

func (q *Queries) GetPostBasicInfo(ctx context.Context, postID []byte) (GetPostBasicInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getPostBasicInfo, postID)
	var i GetPostBasicInfoRow
	err := row.Scan(&i.PostID, &i.AuthorID, &i.Visibility)
	return i, err
}

const getPostComments = `-- name: GetPostComments :many
SELECT comment_id, post_id, user_id, parent_comment_id, content, image_id, created_at FROM comments WHERE post_id = ?
`

func (q *Queries) GetPostComments(ctx context.Context, postID string) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, getPostComments, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.CommentID,
			&i.PostID,
			&i.UserID,
			&i.ParentCommentID,
			&i.Content,
			&i.ImageID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostReactions = `-- name: GetPostReactions :many
SELECT reaction_id, user_id, target_type, target_id, reaction_type, reacted_at FROM reactions WHERE target_type = 'post' AND target_id = ?
`

func (q *Queries) GetPostReactions(ctx context.Context, targetID string) ([]Reaction, error) {
	rows, err := q.db.QueryContext(ctx, getPostReactions, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reaction
	for rows.Next() {
		var i Reaction
		if err := rows.Scan(
			&i.ReactionID,
			&i.UserID,
			&i.TargetType,
			&i.TargetID,
			&i.ReactionType,
			&i.ReactedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostVisibility = `-- name: GetPostVisibility :one
SELECT visibility FROM posts WHERE post_id = ?
`

func (q *Queries) GetPostVisibility(ctx context.Context, postID []byte) (string, error) {
	row := q.db.QueryRowContext(ctx, getPostVisibility, postID)
	var visibility string
	err := row.Scan(&visibility)
	return visibility, err
}

const getPostWithReactionsAndComments = `-- name: GetPostWithReactionsAndComments :one
SELECT
    p.post_id, p.author_id, p.content, p.image_id, p.visibility, p.created_at,
    (SELECT COALESCE(json_group_array(json_object(
        'reaction_id', r.reaction_id,
        'user_id', r.user_id,
        'reaction_type', r.reaction_type
                                  )), '[]')
    FROM reactions r WHERE r.target_type = 'post' AND r.target_id = p.post_id) as reactions,
    (SELECT COALESCE(json_group_array(json_object(
        'comment_id', c.comment_id,
        'user_id', c.user_id,
        'content', c.content,
        'reactions', (
            SELECT COALESCE(json_group_array(json_object(
                'reaction_id', cr.reaction_id,
                'user_id', cr.user_id,
                'reaction_type', cr.reaction_type
            )), '[]')
            FROM reactions cr
            WHERE cr.target_type = 'comment' AND cr.target_id = c.comment_id
        )
    )), '[]')
    FROM comments c WHERE c.post_id = p.post_id) as comments
FROM posts p
WHERE p.post_id = ?
`

type GetPostWithReactionsAndCommentsRow struct {
	PostID     []byte
	AuthorID   []byte
	Content    string
	ImageID    sql.NullString
	Visibility string
	CreatedAt  sql.NullTime
	Reactions  interface{}
	Comments   interface{}
}

func (q *Queries) GetPostWithReactionsAndComments(ctx context.Context, postID []byte) (GetPostWithReactionsAndCommentsRow, error) {
	row := q.db.QueryRowContext(ctx, getPostWithReactionsAndComments, postID)
	var i GetPostWithReactionsAndCommentsRow
	err := row.Scan(
		&i.PostID,
		&i.AuthorID,
		&i.Content,
		&i.ImageID,
		&i.Visibility,
		&i.CreatedAt,
		&i.Reactions,
		&i.Comments,
	)
	return i, err
}

const getPostsForFeed = `-- name: GetPostsForFeed :many
SELECT p.post_id, p.author_id, p.content, p.image_id, p.visibility, p.created_at,
       (SELECT COUNT(*)
        FROM reactions
        WHERE target_type = 'post'
          AND target_id = p.post_id) as reaction_count,
       (SELECT COUNT(*)
        FROM comments
        WHERE post_id = p.post_id)   as comment_count
FROM posts p
INNER JOIN users u ON p.author_id = u.user_id
WHERE
   -- Public posts from any user
    (p.visibility = 'public')
   OR
   -- Private posts where current user follows the author
    (p.visibility = 'private' AND EXISTS (SELECT 1
                                          FROM followers f
                                          WHERE f.follower_id = ?
                                            AND f.followee_id = p.author_id))
   OR
   -- Private posts where current user has explicit viewing permission
    (p.visibility = 'private' AND EXISTS (SELECT 1
                                          FROM viewing_permissions vp
                                          WHERE vp.user_id = ?
                                            AND vp.post_id = p.post_id))
ORDER BY p.created_at DESC LIMIT ?
OFFSET ?
`

type GetPostsForFeedParams struct {
	FollowerID []byte
	UserID     []byte
	Limit      int64
	Offset     int64
}

type GetPostsForFeedRow struct {
	PostID        []byte
	AuthorID      []byte
	Content       string
	ImageID       sql.NullString
	Visibility    string
	CreatedAt     sql.NullTime
	ReactionCount int64
	CommentCount  int64
}

func (q *Queries) GetPostsForFeed(ctx context.Context, arg GetPostsForFeedParams) ([]GetPostsForFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsForFeed,
		arg.FollowerID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsForFeedRow
	for rows.Next() {
		var i GetPostsForFeedRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.Content,
			&i.ImageID,
			&i.Visibility,
			&i.CreatedAt,
			&i.ReactionCount,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePrivatePostViewingPermission = `-- name: RemovePrivatePostViewingPermission :exec
DELETE FROM viewing_permissions WHERE user_id = ? AND post_id = ?
`

type RemovePrivatePostViewingPermissionParams struct {
	UserID []byte
	PostID string
}

func (q *Queries) RemovePrivatePostViewingPermission(ctx context.Context, arg RemovePrivatePostViewingPermissionParams) error {
	_, err := q.db.ExecContext(ctx, removePrivatePostViewingPermission, arg.UserID, arg.PostID)
	return err
}

const updatePost = `-- name: UpdatePost :exec
UPDATE posts SET content = ? AND image_id = ? WHERE post_id = ? and author_id = ?
`

type UpdatePostParams struct {
	Content  string
	ImageID  sql.NullString
	PostID   []byte
	AuthorID []byte
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) error {
	_, err := q.db.ExecContext(ctx, updatePost,
		arg.Content,
		arg.ImageID,
		arg.PostID,
		arg.AuthorID,
	)
	return err
}
