// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package db_posts

import (
	"context"
	"database/sql"
)

const addPrivatePostViewingPermission = `-- name: AddPrivatePostViewingPermission :execrows
INSERT INTO viewing_permissions (user_id, post_id)
SELECT ?, ?
    WHERE EXISTS (
    SELECT 1 FROM posts p
    WHERE p.post_id = ?
      AND p.visibility = 'private'
      AND EXISTS (
          SELECT 1 FROM followers f
          WHERE f.follower_id = ?
            AND f.followee_id = p.author_id
      )
)
`

type AddPrivatePostViewingPermissionParams struct {
	UserID     []byte
	PostID     []byte
	PostID_2   []byte
	FollowerID []byte
}

func (q *Queries) AddPrivatePostViewingPermission(ctx context.Context, arg AddPrivatePostViewingPermissionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addPrivatePostViewingPermission,
		arg.UserID,
		arg.PostID,
		arg.PostID_2,
		arg.FollowerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const addViewingPermission = `-- name: AddViewingPermission :exec
INSERT OR IGNORE INTO viewing_permissions (user_id, post_id) VALUES (?, ?)
`

type AddViewingPermissionParams struct {
	UserID []byte
	PostID []byte
}

func (q *Queries) AddViewingPermission(ctx context.Context, arg AddViewingPermissionParams) error {
	_, err := q.db.ExecContext(ctx, addViewingPermission, arg.UserID, arg.PostID)
	return err
}

const checkCommentExists = `-- name: CheckCommentExists :one
SELECT EXISTS(SELECT 1 FROM comments WHERE comment_id = ?)
`

func (q *Queries) CheckCommentExists(ctx context.Context, commentID []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkCommentExists, commentID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const checkCommentHasChildren = `-- name: CheckCommentHasChildren :one
SELECT COUNT(*) FROM comments WHERE parent_comment_id = ?
`

func (q *Queries) CheckCommentHasChildren(ctx context.Context, parentCommentID []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkCommentHasChildren, parentCommentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const checkPrivatePostUserPermit = `-- name: CheckPrivatePostUserPermit :one
SELECT post_id, user_id, created_at FROM viewing_permissions WHERE user_id = ? AND post_id = ?
`

type CheckPrivatePostUserPermitParams struct {
	UserID []byte
	PostID []byte
}

func (q *Queries) CheckPrivatePostUserPermit(ctx context.Context, arg CheckPrivatePostUserPermitParams) (ViewingPermission, error) {
	row := q.db.QueryRowContext(ctx, checkPrivatePostUserPermit, arg.UserID, arg.PostID)
	var i ViewingPermission
	err := row.Scan(&i.PostID, &i.UserID, &i.CreatedAt)
	return i, err
}

const createComment = `-- name: CreateComment :execrows
INSERT INTO comments (comment_id, post_id, author_id, content, parent_comment_id, image_id)
SELECT ?, ?, ?, ?, ?, ?
    WHERE EXISTS (
    SELECT 1 FROM posts p
    WHERE p.post_id = ?
)
`

type CreateCommentParams struct {
	CommentID       []byte
	PostID          []byte
	AuthorID        []byte
	Content         string
	ParentCommentID []byte
	ImageID         sql.NullString
	PostID_2        []byte
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createComment,
		arg.CommentID,
		arg.PostID,
		arg.AuthorID,
		arg.Content,
		arg.ParentCommentID,
		arg.ImageID,
		arg.PostID_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createGroupPost = `-- name: CreateGroupPost :one
INSERT INTO posts (post_id, author_id, content, visibility, image_id, group_id)
VALUES (?, ?, ?, 'group', ?, ?)
RETURNING post_id, author_id, content, image_id, visibility, created_at, group_id
`

type CreateGroupPostParams struct {
	PostID   []byte
	AuthorID []byte
	Content  string
	ImageID  sql.NullString
	GroupID  []byte
}

func (q *Queries) CreateGroupPost(ctx context.Context, arg CreateGroupPostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createGroupPost,
		arg.PostID,
		arg.AuthorID,
		arg.Content,
		arg.ImageID,
		arg.GroupID,
	)
	var i Post
	err := row.Scan(
		&i.PostID,
		&i.AuthorID,
		&i.Content,
		&i.ImageID,
		&i.Visibility,
		&i.CreatedAt,
		&i.GroupID,
	)
	return i, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (post_id, author_id, content, visibility, image_id) VALUES (?, ?, ?, ?, ?) RETURNING post_id, author_id, content, image_id, visibility, created_at, group_id
`

type CreatePostParams struct {
	PostID     []byte
	AuthorID   []byte
	Content    string
	Visibility string
	ImageID    sql.NullString
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.PostID,
		arg.AuthorID,
		arg.Content,
		arg.Visibility,
		arg.ImageID,
	)
	var i Post
	err := row.Scan(
		&i.PostID,
		&i.AuthorID,
		&i.Content,
		&i.ImageID,
		&i.Visibility,
		&i.CreatedAt,
		&i.GroupID,
	)
	return i, err
}

const createReaction = `-- name: CreateReaction :execrows
INSERT INTO reactions (reaction_id, target_type, target_id, author_id)
SELECT ?, ?, ?, ?
    WHERE EXISTS (
    SELECT 1 FROM posts p
    WHERE p.post_id = ?
)
`

type CreateReactionParams struct {
	ReactionID []byte
	TargetType string
	TargetID   []byte
	AuthorID   []byte
	PostID     []byte
}

func (q *Queries) CreateReaction(ctx context.Context, arg CreateReactionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createReaction,
		arg.ReactionID,
		arg.TargetType,
		arg.TargetID,
		arg.AuthorID,
		arg.PostID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE comment_id = ? AND author_id = ?
`

type DeleteCommentParams struct {
	CommentID []byte
	AuthorID  []byte
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) error {
	_, err := q.db.ExecContext(ctx, deleteComment, arg.CommentID, arg.AuthorID)
	return err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE post_id = ? and author_id = ?
`

type DeletePostParams struct {
	PostID   []byte
	AuthorID []byte
}

func (q *Queries) DeletePost(ctx context.Context, arg DeletePostParams) error {
	_, err := q.db.ExecContext(ctx, deletePost, arg.PostID, arg.AuthorID)
	return err
}

const deleteReaction = `-- name: DeleteReaction :exec
DELETE FROM reactions WHERE author_id = ? AND target_type = ? AND target_id = ?
`

type DeleteReactionParams struct {
	AuthorID   []byte
	TargetType string
	TargetID   []byte
}

func (q *Queries) DeleteReaction(ctx context.Context, arg DeleteReactionParams) error {
	_, err := q.db.ExecContext(ctx, deleteReaction, arg.AuthorID, arg.TargetType, arg.TargetID)
	return err
}

const editComment = `-- name: EditComment :exec
UPDATE comments SET content = ?, image_id = ? WHERE comment_id = ? AND author_id = ?
`

type EditCommentParams struct {
	Content   string
	ImageID   sql.NullString
	CommentID []byte
	AuthorID  []byte
}

func (q *Queries) EditComment(ctx context.Context, arg EditCommentParams) error {
	_, err := q.db.ExecContext(ctx, editComment,
		arg.Content,
		arg.ImageID,
		arg.CommentID,
		arg.AuthorID,
	)
	return err
}

const editPostVisibility = `-- name: EditPostVisibility :exec
UPDATE posts SET visibility = ? WHERE post_id = ? and author_id = ?
`

type EditPostVisibilityParams struct {
	Visibility string
	PostID     []byte
	AuthorID   []byte
}

func (q *Queries) EditPostVisibility(ctx context.Context, arg EditPostVisibilityParams) error {
	_, err := q.db.ExecContext(ctx, editPostVisibility, arg.Visibility, arg.PostID, arg.AuthorID)
	return err
}

const findUserReaction = `-- name: FindUserReaction :one
SELECT reaction_id FROM reactions WHERE author_id = ? AND target_type = ? AND target_id = ?
`

type FindUserReactionParams struct {
	AuthorID   []byte
	TargetType string
	TargetID   []byte
}

func (q *Queries) FindUserReaction(ctx context.Context, arg FindUserReactionParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, findUserReaction, arg.AuthorID, arg.TargetType, arg.TargetID)
	var reaction_id []byte
	err := row.Scan(&reaction_id)
	return reaction_id, err
}

const getCommentById = `-- name: GetCommentById :one
SELECT comment_id, post_id, author_id, parent_comment_id, content, image_id, created_at FROM comments WHERE comment_id = ? LIMIT 1
`

func (q *Queries) GetCommentById(ctx context.Context, commentID []byte) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getCommentById, commentID)
	var i Comment
	err := row.Scan(
		&i.CommentID,
		&i.PostID,
		&i.AuthorID,
		&i.ParentCommentID,
		&i.Content,
		&i.ImageID,
		&i.CreatedAt,
	)
	return i, err
}

const getFeedPostsCount = `-- name: GetFeedPostsCount :one
SELECT COUNT(*)
FROM posts p
         INNER JOIN users u ON p.author_id = u.user_id
WHERE
    (p.author_id = ?)
   OR
   -- Public posts from any user
    (p.visibility = 'public')
   OR
   -- Private posts where current user follows the author
    (p.visibility = 'semi-private' AND EXISTS (SELECT 1
                                               FROM followers f
                                               WHERE f.follower_id = ?
                                                 AND f.followee_id = p.author_id))
   OR
   -- Private posts where current user has explicit viewing permission
    (p.visibility = 'private' AND EXISTS (SELECT 1
                                          FROM viewing_permissions vp
                                          WHERE vp.user_id = ?
                                            AND vp.post_id = p.post_id))
   OR
   -- Group posts
    (p.visibility = 'group' AND EXISTS( SELECT 1
                                        FROM group_members gm
                                        WHERE p.group_id = gm.group_id
                                          AND gm.user_id = ?))
`

type GetFeedPostsCountParams struct {
	AuthorID   []byte
	FollowerID []byte
	UserID     []byte
	UserID_2   []byte
}

func (q *Queries) GetFeedPostsCount(ctx context.Context, arg GetFeedPostsCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getFeedPostsCount,
		arg.AuthorID,
		arg.FollowerID,
		arg.UserID,
		arg.UserID_2,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getGroupPosts = `-- name: GetGroupPosts :many
SELECT p.post_id, p.author_id, p.content, p.image_id, p.visibility, p.created_at, p.group_id,
       u.first_name, u.last_name, u.nickname, u.avatar,
       i.image_id as post_image_id,
       i.image_path,
       i.file_name,
       (SELECT COUNT(*) FROM reactions r WHERE r.target_type='post' AND r.target_id=p.post_id) as reaction_count,
       (SELECT COUNT(*) FROM comments c WHERE c.post_id=p.post_id) as comment_count,
       EXISTS(SELECT 1 FROM reactions r WHERE r.target_type='post' AND r.target_id=p.post_id AND r.author_id=?) as user_reacted
FROM posts p
JOIN users u ON p.author_id = u.user_id
LEFT JOIN images i ON p.image_id = i.image_id
WHERE p.group_id = ?
ORDER BY p.created_at DESC
LIMIT ? OFFSET ?
`

type GetGroupPostsParams struct {
	AuthorID []byte
	GroupID  []byte
	Limit    int64
	Offset   int64
}

type GetGroupPostsRow struct {
	PostID        []byte
	AuthorID      []byte
	Content       string
	ImageID       sql.NullString
	Visibility    string
	CreatedAt     sql.NullTime
	GroupID       []byte
	FirstName     string
	LastName      string
	Nickname      sql.NullString
	Avatar        sql.NullString
	PostImageID   sql.NullString
	ImagePath     sql.NullString
	FileName      sql.NullString
	ReactionCount int64
	CommentCount  int64
	UserReacted   int64
}

func (q *Queries) GetGroupPosts(ctx context.Context, arg GetGroupPostsParams) ([]GetGroupPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupPosts,
		arg.AuthorID,
		arg.GroupID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupPostsRow
	for rows.Next() {
		var i GetGroupPostsRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.Content,
			&i.ImageID,
			&i.Visibility,
			&i.CreatedAt,
			&i.GroupID,
			&i.FirstName,
			&i.LastName,
			&i.Nickname,
			&i.Avatar,
			&i.PostImageID,
			&i.ImagePath,
			&i.FileName,
			&i.ReactionCount,
			&i.CommentCount,
			&i.UserReacted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupPostsCount = `-- name: GetGroupPostsCount :one
SELECT COUNT(*) FROM posts p WHERE p.group_id = ?
`

func (q *Queries) GetGroupPostsCount(ctx context.Context, groupID []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, getGroupPostsCount, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPostBasicInfo = `-- name: GetPostBasicInfo :one
SELECT post_id, author_id, visibility, group_id FROM posts WHERE post_id = ?
`

type GetPostBasicInfoRow struct {
	PostID     []byte
	AuthorID   []byte
	Visibility string
	GroupID    []byte
}

func (q *Queries) GetPostBasicInfo(ctx context.Context, postID []byte) (GetPostBasicInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getPostBasicInfo, postID)
	var i GetPostBasicInfoRow
	err := row.Scan(
		&i.PostID,
		&i.AuthorID,
		&i.Visibility,
		&i.GroupID,
	)
	return i, err
}

const getPostByID = `-- name: GetPostByID :one
SELECT p.post_id, p.author_id, p.content, p.image_id, p.visibility, p.created_at, p.group_id, u.first_name, u.last_name, u.nickname, u.avatar, i.file_name
FROM posts p
JOIN users u ON p.author_id = u.user_id
LEFT JOIN images i ON p.image_id = i.image_id
WHERE p.post_id = ?
`

type GetPostByIDRow struct {
	PostID     []byte
	AuthorID   []byte
	Content    string
	ImageID    sql.NullString
	Visibility string
	CreatedAt  sql.NullTime
	GroupID    []byte
	FirstName  string
	LastName   string
	Nickname   sql.NullString
	Avatar     sql.NullString
	FileName   sql.NullString
}

func (q *Queries) GetPostByID(ctx context.Context, postID []byte) (GetPostByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPostByID, postID)
	var i GetPostByIDRow
	err := row.Scan(
		&i.PostID,
		&i.AuthorID,
		&i.Content,
		&i.ImageID,
		&i.Visibility,
		&i.CreatedAt,
		&i.GroupID,
		&i.FirstName,
		&i.LastName,
		&i.Nickname,
		&i.Avatar,
		&i.FileName,
	)
	return i, err
}

const getPostComments = `-- name: GetPostComments :many
SELECT
    c.comment_id, c.post_id, c.author_id, c.parent_comment_id, c.content, c.image_id, c.created_at,
    u.first_name, u.last_name, u.nickname, u.avatar,
    i.file_name,
    COUNT(r.reaction_id) as reaction_count,
    EXISTS(
        SELECT 1 FROM reactions r
        WHERE target_type = 'comment'
          AND r.target_id = c.comment_id
          AND r.author_id = ?
    ) as user_reacted
FROM comments c
         JOIN users u ON c.author_id = u.user_id
         LEFT JOIN images i ON c.image_id = i.image_id
         LEFT JOIN reactions r ON r.target_type = 'comment' AND r.target_id = c.comment_id
WHERE c.post_id = ?
GROUP BY c.comment_id
ORDER BY c.created_at ASC
`

type GetPostCommentsParams struct {
	AuthorID []byte
	PostID   []byte
}

type GetPostCommentsRow struct {
	CommentID       []byte
	PostID          []byte
	AuthorID        []byte
	ParentCommentID []byte
	Content         string
	ImageID         sql.NullString
	CreatedAt       sql.NullTime
	FirstName       string
	LastName        string
	Nickname        sql.NullString
	Avatar          sql.NullString
	FileName        sql.NullString
	ReactionCount   int64
	UserReacted     int64
}

func (q *Queries) GetPostComments(ctx context.Context, arg GetPostCommentsParams) ([]GetPostCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostComments, arg.AuthorID, arg.PostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostCommentsRow
	for rows.Next() {
		var i GetPostCommentsRow
		if err := rows.Scan(
			&i.CommentID,
			&i.PostID,
			&i.AuthorID,
			&i.ParentCommentID,
			&i.Content,
			&i.ImageID,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
			&i.Nickname,
			&i.Avatar,
			&i.FileName,
			&i.ReactionCount,
			&i.UserReacted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostReactions = `-- name: GetPostReactions :one
SELECT COUNT(*) FROM reactions WHERE target_type = 'post' AND target_id = ?
`

func (q *Queries) GetPostReactions(ctx context.Context, targetID []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPostReactions, targetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPostVisibility = `-- name: GetPostVisibility :one
SELECT visibility FROM posts WHERE post_id = ?
`

func (q *Queries) GetPostVisibility(ctx context.Context, postID []byte) (string, error) {
	row := q.db.QueryRowContext(ctx, getPostVisibility, postID)
	var visibility string
	err := row.Scan(&visibility)
	return visibility, err
}

const getPostsForFeed = `-- name: GetPostsForFeed :many
SELECT p.post_id, p.author_id, p.content, p.image_id, p.visibility, p.created_at, p.group_id,
       u.first_name, u.last_name, u.nickname, u.avatar,
       i.image_id as post_image_id,
       i.image_path,
       i.file_name,
       (SELECT COUNT(*)
        FROM reactions
        WHERE target_type = 'post'
          AND target_id = p.post_id) as reaction_count,
       (SELECT COUNT(*)
        FROM comments
        WHERE post_id = p.post_id)   as comment_count,
       EXISTS(SELECT 1
              FROM reactions r
              WHERE r.target_type = 'post'
                AND r.target_id = p.post_id
                AND r.author_id = ?) as user_reacted
FROM posts p
INNER JOIN users u ON p.author_id = u.user_id
LEFT JOIN images i ON p.image_id = i.image_id
WHERE
    (p.author_id = ?)
    OR
   -- Public posts from any user
    (p.visibility = 'public')
   OR
   -- Private posts where current user follows the author
    (p.visibility = 'semi-private' AND EXISTS (SELECT 1
                                          FROM followers f
                                          WHERE f.follower_id = ?
                                            AND f.followee_id = p.author_id))
   OR
   -- Private posts where current user has explicit viewing permission
    (p.visibility = 'private' AND EXISTS (SELECT 1
                                          FROM viewing_permissions vp
                                          WHERE vp.user_id = ?
                                            AND vp.post_id = p.post_id))
    OR
    -- Group posts
    (p.visibility = 'group' AND EXISTS( SELECT 1
                                        FROM group_members gm
                                        WHERE p.group_id = gm.group_id
                                        AND gm.user_id = ?))
ORDER BY p.created_at DESC LIMIT ?
OFFSET ?
`

type GetPostsForFeedParams struct {
	AuthorID   []byte
	AuthorID_2 []byte
	FollowerID []byte
	UserID     []byte
	UserID_2   []byte
	Limit      int64
	Offset     int64
}

type GetPostsForFeedRow struct {
	PostID        []byte
	AuthorID      []byte
	Content       string
	ImageID       sql.NullString
	Visibility    string
	CreatedAt     sql.NullTime
	GroupID       []byte
	FirstName     string
	LastName      string
	Nickname      sql.NullString
	Avatar        sql.NullString
	PostImageID   sql.NullString
	ImagePath     sql.NullString
	FileName      sql.NullString
	ReactionCount int64
	CommentCount  int64
	UserReacted   int64
}

func (q *Queries) GetPostsForFeed(ctx context.Context, arg GetPostsForFeedParams) ([]GetPostsForFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsForFeed,
		arg.AuthorID,
		arg.AuthorID_2,
		arg.FollowerID,
		arg.UserID,
		arg.UserID_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsForFeedRow
	for rows.Next() {
		var i GetPostsForFeedRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.Content,
			&i.ImageID,
			&i.Visibility,
			&i.CreatedAt,
			&i.GroupID,
			&i.FirstName,
			&i.LastName,
			&i.Nickname,
			&i.Avatar,
			&i.PostImageID,
			&i.ImagePath,
			&i.FileName,
			&i.ReactionCount,
			&i.CommentCount,
			&i.UserReacted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPosts = `-- name: GetUserPosts :many
SELECT p.post_id, p.author_id, p.content, p.image_id, p.visibility, p.created_at, p.group_id,
       u.first_name, u.last_name, u.nickname, u.avatar,
       i.image_id as post_image_id,
       i.image_path,
       i.file_name,
       (SELECT COUNT(*)
        FROM reactions
        WHERE target_type = 'post'
          AND target_id = p.post_id) as reaction_count,
       (SELECT COUNT(*)
        FROM comments
        WHERE post_id = p.post_id)   as comment_count,
       EXISTS(SELECT 1
              FROM reactions r
              WHERE r.target_type = 'post'
                AND r.target_id = p.post_id
                AND r.author_id = ?) as user_reacted
FROM posts p
JOIN users u ON p.author_id = u.user_id
LEFT JOIN images i ON p.image_id = i.image_id
WHERE p.author_id = ?
  AND (
    p.visibility = 'public'
    OR (p.visibility = 'semi-private' AND EXISTS(
        SELECT 1 FROM followers WHERE follower_id = ? OR followee_id = p.author_id
    ))
    OR (p.visibility = 'private' AND (
        p.author_id = ? OR EXISTS(SELECT 1 FROM viewing_permissions vp WHERE vp.user_id = ? AND vp.post_id = p.post_id)
    ))
  )
ORDER BY p.created_at DESC
LIMIT ? OFFSET ?
`

type GetUserPostsParams struct {
	AuthorID   []byte
	AuthorID_2 []byte
	FollowerID []byte
	AuthorID_3 []byte
	UserID     []byte
	Limit      int64
	Offset     int64
}

type GetUserPostsRow struct {
	PostID        []byte
	AuthorID      []byte
	Content       string
	ImageID       sql.NullString
	Visibility    string
	CreatedAt     sql.NullTime
	GroupID       []byte
	FirstName     string
	LastName      string
	Nickname      sql.NullString
	Avatar        sql.NullString
	PostImageID   sql.NullString
	ImagePath     sql.NullString
	FileName      sql.NullString
	ReactionCount int64
	CommentCount  int64
	UserReacted   int64
}

func (q *Queries) GetUserPosts(ctx context.Context, arg GetUserPostsParams) ([]GetUserPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserPosts,
		arg.AuthorID,
		arg.AuthorID_2,
		arg.FollowerID,
		arg.AuthorID_3,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserPostsRow
	for rows.Next() {
		var i GetUserPostsRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.Content,
			&i.ImageID,
			&i.Visibility,
			&i.CreatedAt,
			&i.GroupID,
			&i.FirstName,
			&i.LastName,
			&i.Nickname,
			&i.Avatar,
			&i.PostImageID,
			&i.ImagePath,
			&i.FileName,
			&i.ReactionCount,
			&i.CommentCount,
			&i.UserReacted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const grantViewingPermissionsToFollower = `-- name: GrantViewingPermissionsToFollower :exec
INSERT OR IGNORE INTO viewing_permissions (user_id, post_id)
SELECT ?, post_id
FROM posts
WHERE author_id = ?
  AND visibility = 'private'
`

type GrantViewingPermissionsToFollowerParams struct {
	UserID   []byte
	AuthorID []byte
}

func (q *Queries) GrantViewingPermissionsToFollower(ctx context.Context, arg GrantViewingPermissionsToFollowerParams) error {
	_, err := q.db.ExecContext(ctx, grantViewingPermissionsToFollower, arg.UserID, arg.AuthorID)
	return err
}

const hasUserReacted = `-- name: HasUserReacted :one
SELECT COUNT(*) FROM reactions WHERE author_id = ? AND target_type = ? AND target_id = ? LIMIT 1
`

type HasUserReactedParams struct {
	AuthorID   []byte
	TargetType string
	TargetID   []byte
}

func (q *Queries) HasUserReacted(ctx context.Context, arg HasUserReactedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasUserReacted, arg.AuthorID, arg.TargetType, arg.TargetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const postVisibilityPublicBatch = `-- name: PostVisibilityPublicBatch :exec
UPDATE posts SET visibility = 'public' WHERE author_id = ? and visibility = 'semi-private'
`

func (q *Queries) PostVisibilityPublicBatch(ctx context.Context, authorID []byte) error {
	_, err := q.db.ExecContext(ctx, postVisibilityPublicBatch, authorID)
	return err
}

const postVisibilitySemiPrivateBatch = `-- name: PostVisibilitySemiPrivateBatch :exec
UPDATE posts SET visibility = 'semi-private' WHERE author_id = ? and visibility = 'public'
`

func (q *Queries) PostVisibilitySemiPrivateBatch(ctx context.Context, authorID []byte) error {
	_, err := q.db.ExecContext(ctx, postVisibilitySemiPrivateBatch, authorID)
	return err
}

const removePrivatePostViewingPermission = `-- name: RemovePrivatePostViewingPermission :exec
DELETE FROM viewing_permissions WHERE user_id = ? AND post_id = ?
`

type RemovePrivatePostViewingPermissionParams struct {
	UserID []byte
	PostID []byte
}

func (q *Queries) RemovePrivatePostViewingPermission(ctx context.Context, arg RemovePrivatePostViewingPermissionParams) error {
	_, err := q.db.ExecContext(ctx, removePrivatePostViewingPermission, arg.UserID, arg.PostID)
	return err
}

const removeViewingPermissionPostIDBatch = `-- name: RemoveViewingPermissionPostIDBatch :exec
DELETE FROM viewing_permissions WHERE post_id = ?
`

func (q *Queries) RemoveViewingPermissionPostIDBatch(ctx context.Context, postID []byte) error {
	_, err := q.db.ExecContext(ctx, removeViewingPermissionPostIDBatch, postID)
	return err
}

const removeViewingPermissionUserIDBatch = `-- name: RemoveViewingPermissionUserIDBatch :exec
DELETE FROM viewing_permissions
WHERE user_id = ?
  AND post_id IN (
    SELECT post_id FROM posts WHERE author_id = ?
)
`

type RemoveViewingPermissionUserIDBatchParams struct {
	UserID   []byte
	AuthorID []byte
}

func (q *Queries) RemoveViewingPermissionUserIDBatch(ctx context.Context, arg RemoveViewingPermissionUserIDBatchParams) error {
	_, err := q.db.ExecContext(ctx, removeViewingPermissionUserIDBatch, arg.UserID, arg.AuthorID)
	return err
}

const updatePost = `-- name: UpdatePost :exec
UPDATE posts SET content = ?, image_id = ? WHERE post_id = ? and author_id = ?
`

type UpdatePostParams struct {
	Content  string
	ImageID  sql.NullString
	PostID   []byte
	AuthorID []byte
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) error {
	_, err := q.db.ExecContext(ctx, updatePost,
		arg.Content,
		arg.ImageID,
		arg.PostID,
		arg.AuthorID,
	)
	return err
}
