// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: followers.sql

package db_followers

import (
	"context"
)

const checkIfUserFollows = `-- name: CheckIfUserFollows :one
SELECT follower_id, followee_id, status, created_at FROM followers WHERE follower_id = ? AND followee_id = ?
`

type CheckIfUserFollowsParams struct {
	FollowerID []byte
	FolloweeID []byte
}

func (q *Queries) CheckIfUserFollows(ctx context.Context, arg CheckIfUserFollowsParams) (Follower, error) {
	row := q.db.QueryRowContext(ctx, checkIfUserFollows, arg.FollowerID, arg.FolloweeID)
	var i Follower
	err := row.Scan(
		&i.FollowerID,
		&i.FolloweeID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
