// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_followers

import (
	"database/sql"
)

type Follower struct {
	FollowerID []byte
	FolloweeID []byte
	CreatedAt  sql.NullTime
}
