// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_users

import (
	"database/sql"
)

type User struct {
	UserID       []byte
	Email        string
	PasswordHash []byte
	FirstName    string
	LastName     string
	Dob          string
	Avatar       sql.NullString
	Nickname     string
	AboutMe      sql.NullString
	IsPublic     sql.NullBool
	CreatedAt    sql.NullTime
}
