// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db_users

import (
	"context"
	"database/sql"
	"strings"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (user_id, email, password_hash, first_name, last_name, dob, avatar, nickname, about_me, is_public)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 0)
RETURNING user_id, email, password_hash, first_name, last_name, dob, avatar, nickname, about_me, is_public, created_at
`

type CreateUserParams struct {
	UserID       []byte
	Email        string
	PasswordHash []byte
	FirstName    string
	LastName     string
	Dob          string
	Avatar       sql.NullString
	Nickname     sql.NullString
	AboutMe      sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.UserID,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.Dob,
		arg.Avatar,
		arg.Nickname,
		arg.AboutMe,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Dob,
		&i.Avatar,
		&i.Nickname,
		&i.AboutMe,
		&i.IsPublic,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, email, password_hash, first_name, last_name, dob, avatar, nickname, about_me, is_public, created_at FROM users WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Dob,
		&i.Avatar,
		&i.Nickname,
		&i.AboutMe,
		&i.IsPublic,
		&i.CreatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT user_id, email, password_hash, first_name, last_name, dob, avatar, nickname, about_me, is_public, created_at
FROM users
WHERE user_id = ?
LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, userID []byte) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Dob,
		&i.Avatar,
		&i.Nickname,
		&i.AboutMe,
		&i.IsPublic,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByNickname = `-- name: GetUserByNickname :one
SELECT user_id, email, password_hash, first_name, last_name, dob, avatar, nickname, about_me, is_public, created_at FROM users WHERE nickname = ? LIMIT 1
`

func (q *Queries) GetUserByNickname(ctx context.Context, nickname sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByNickname, nickname)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Dob,
		&i.Avatar,
		&i.Nickname,
		&i.AboutMe,
		&i.IsPublic,
		&i.CreatedAt,
	)
	return i, err
}

const queryUsers = `-- name: QueryUsers :many
SELECT
    u.user_id,
    u.first_name,
    u.last_name,
    u.nickname,
    u.avatar
FROM users u
WHERE (
    LOWER(u.first_name || '') LIKE LOWER('%' || ? || '%')
    OR LOWER(u.last_name || '') LIKE LOWER('%' || ? || '%')
    OR LOWER(COALESCE(u.nickname, '')) LIKE LOWER('%' || ? || '%')
)
`

type QueryUsersParams struct {
	Column1 sql.NullString
	Column2 sql.NullString
	Column3 sql.NullString
}

type QueryUsersRow struct {
	UserID    []byte
	FirstName string
	LastName  string
	Nickname  sql.NullString
	Avatar    sql.NullString
}

func (q *Queries) QueryUsers(ctx context.Context, arg QueryUsersParams) ([]QueryUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, queryUsers, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryUsersRow
	for rows.Next() {
		var i QueryUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.Nickname,
			&i.Avatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET first_name = ?, last_name = ?, nickname = ?, about_me = ?, avatar = ? WHERE user_id = ? RETURNING user_id, email, password_hash, first_name, last_name, dob, avatar, nickname, about_me, is_public, created_at
`

type UpdateUserParams struct {
	FirstName string
	LastName  string
	Nickname  sql.NullString
	AboutMe   sql.NullString
	Avatar    sql.NullString
	UserID    []byte
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.Nickname,
		arg.AboutMe,
		arg.Avatar,
		arg.UserID,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Dob,
		&i.Avatar,
		&i.Nickname,
		&i.AboutMe,
		&i.IsPublic,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserPrivacy = `-- name: UpdateUserPrivacy :one
UPDATE users SET is_public = ? WHERE user_id = ? RETURNING user_id, email, password_hash, first_name, last_name, dob, avatar, nickname, about_me, is_public, created_at
`

type UpdateUserPrivacyParams struct {
	IsPublic bool
	UserID   []byte
}

func (q *Queries) UpdateUserPrivacy(ctx context.Context, arg UpdateUserPrivacyParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPrivacy, arg.IsPublic, arg.UserID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Dob,
		&i.Avatar,
		&i.Nickname,
		&i.AboutMe,
		&i.IsPublic,
		&i.CreatedAt,
	)
	return i, err
}

const validateUserIds = `-- name: ValidateUserIds :one
SELECT COUNT(*) FROM users WHERE user_id IN (/*SLICE:user_id*/?)
`

func (q *Queries) ValidateUserIds(ctx context.Context, userID [][]byte) (int64, error) {
	query := validateUserIds
	var queryParams []interface{}
	if len(userID) > 0 {
		for _, v := range userID {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:user_id*/?", strings.Repeat(",?", len(userID))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:user_id*/?", "NULL", 1)
	}
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var count int64
	err := row.Scan(&count)
	return count, err
}
