// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db_users

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (user_id, email, password_hash, first_name, last_name, dob, avatar, nickname, about_me, is_public)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 0)
RETURNING user_id, email, password_hash, first_name, last_name, dob, avatar, nickname, about_me, is_public, created_at
`

type CreateUserParams struct {
	UserID       []byte
	Email        string
	PasswordHash []byte
	FirstName    string
	LastName     string
	Dob          string
	Avatar       sql.NullString
	Nickname     sql.NullString
	AboutMe      sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.UserID,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.Dob,
		arg.Avatar,
		arg.Nickname,
		arg.AboutMe,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Dob,
		&i.Avatar,
		&i.Nickname,
		&i.AboutMe,
		&i.IsPublic,
		&i.CreatedAt,
	)
	return i, err
}

const gerUserById = `-- name: GerUserById :one
SELECT user_id, email, password_hash, first_name, last_name, dob, avatar, nickname, about_me, is_public, created_at
FROM users
WHERE user_id = ?
LIMIT 1
`

func (q *Queries) GerUserById(ctx context.Context, userID []byte) (User, error) {
	row := q.db.QueryRowContext(ctx, gerUserById, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Dob,
		&i.Avatar,
		&i.Nickname,
		&i.AboutMe,
		&i.IsPublic,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, email, password_hash, first_name, last_name, dob, avatar, nickname, about_me, is_public, created_at FROM users WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Dob,
		&i.Avatar,
		&i.Nickname,
		&i.AboutMe,
		&i.IsPublic,
		&i.CreatedAt,
	)
	return i, err
}
