// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_public_images

import (
	"database/sql"
)

type PublicImage struct {
	ImageID      string
	GuestSession []byte
	ImagePath    string
	FileName     string
	CreatedAt    sql.NullTime
	ExpiresAt    sql.NullTime
}
