// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: public_images.sql

package db_public_images

import (
	"context"
	"strings"
)

const deletePublicImage = `-- name: DeletePublicImage :exec
DELETE FROM public_images WHERE image_id = ?
`

func (q *Queries) DeletePublicImage(ctx context.Context, imageID string) error {
	_, err := q.db.ExecContext(ctx, deletePublicImage, imageID)
	return err
}

const deletePublicImages = `-- name: DeletePublicImages :exec
DELETE FROM public_images WHERE image_id IN (/*SLICE:image_id*/?)
`

func (q *Queries) DeletePublicImages(ctx context.Context, imageID []string) error {
	query := deletePublicImages
	var queryParams []interface{}
	if len(imageID) > 0 {
		for _, v := range imageID {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:image_id*/?", strings.Repeat(",?", len(imageID))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:image_id*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const getPublicImage = `-- name: GetPublicImage :one
SELECT image_id, guest_session, image_path, file_name, created_at, expires_at FROM public_images WHERE image_id = ? LIMIT 1
`

func (q *Queries) GetPublicImage(ctx context.Context, imageID string) (PublicImage, error) {
	row := q.db.QueryRowContext(ctx, getPublicImage, imageID)
	var i PublicImage
	err := row.Scan(
		&i.ImageID,
		&i.GuestSession,
		&i.ImagePath,
		&i.FileName,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getPublicImages = `-- name: GetPublicImages :many
SELECT image_id, guest_session, image_path, file_name, created_at, expires_at FROM public_images
`

func (q *Queries) GetPublicImages(ctx context.Context) ([]PublicImage, error) {
	rows, err := q.db.QueryContext(ctx, getPublicImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicImage
	for rows.Next() {
		var i PublicImage
		if err := rows.Scan(
			&i.ImageID,
			&i.GuestSession,
			&i.ImagePath,
			&i.FileName,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const savePublicImage = `-- name: SavePublicImage :exec
INSERT INTO public_images (image_id, guest_session, image_path, file_name, created_at, expires_at)
VALUES(?, ?, ?, ?, CAST(? AS TEXT), CAST(? AS TEXT))
`

type SavePublicImageParams struct {
	ImageID      string
	GuestSession []byte
	ImagePath    string
	FileName     string
	Column5      string
	Column6      string
}

func (q *Queries) SavePublicImage(ctx context.Context, arg SavePublicImageParams) error {
	_, err := q.db.ExecContext(ctx, savePublicImage,
		arg.ImageID,
		arg.GuestSession,
		arg.ImagePath,
		arg.FileName,
		arg.Column5,
		arg.Column6,
	)
	return err
}
