// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package db_groups

import (
	"context"
	"database/sql"
	"time"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (group_id, group_name, description, image, creator_id, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING group_id, group_name, description, image, creator_id, created_at
`

type CreateGroupParams struct {
	GroupID     []byte
	GroupName   string
	Description string
	Image       sql.NullString
	CreatorID   []byte
	CreatedAt   time.Time
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup,
		arg.GroupID,
		arg.GroupName,
		arg.Description,
		arg.Image,
		arg.CreatorID,
		arg.CreatedAt,
	)
	var i Group
	err := row.Scan(
		&i.GroupID,
		&i.GroupName,
		&i.Description,
		&i.Image,
		&i.CreatorID,
		&i.CreatedAt,
	)
	return i, err
}

const createGroupMember = `-- name: CreateGroupMember :exec
INSERT INTO group_members (user_id, group_id, status, invited_by, created_at)
VALUES (?, ?, 'joined', NULL, ?)
`

type CreateGroupMemberParams struct {
	UserID    []byte
	GroupID   []byte
	CreatedAt sql.NullTime
}

func (q *Queries) CreateGroupMember(ctx context.Context, arg CreateGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, createGroupMember, arg.UserID, arg.GroupID, arg.CreatedAt)
	return err
}

const getGroupByName = `-- name: GetGroupByName :one
SELECT group_name FROM groups WHERE group_name = ? LIMIT 1
`

func (q *Queries) GetGroupByName(ctx context.Context, groupName string) (string, error) {
	row := q.db.QueryRowContext(ctx, getGroupByName, groupName)
	var group_name string
	err := row.Scan(&group_name)
	return group_name, err
}

const getGroupsWithMemberCount = `-- name: GetGroupsWithMemberCount :many
SELECT
    g.group_id,
    g.group_name,
    g.description,
    g.image,
    g.creator_id,
    g.created_at,
    COUNT(gm.user_id) as member_count
FROM groups g
LEFT JOIN group_members gm ON g.group_id = gm.group_id AND gm.status = 'joined'
GROUP BY g.group_id
ORDER BY g.created_at DESC
`

type GetGroupsWithMemberCountRow struct {
	GroupID     []byte
	GroupName   string
	Description string
	Image       sql.NullString
	CreatorID   []byte
	CreatedAt   time.Time
	MemberCount int64
}

func (q *Queries) GetGroupsWithMemberCount(ctx context.Context) ([]GetGroupsWithMemberCountRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupsWithMemberCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupsWithMemberCountRow
	for rows.Next() {
		var i GetGroupsWithMemberCountRow
		if err := rows.Scan(
			&i.GroupID,
			&i.GroupName,
			&i.Description,
			&i.Image,
			&i.CreatorID,
			&i.CreatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
