// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package db_groups

import (
	"context"
	"database/sql"
	"time"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (group_id, group_name, description, image, creator_id, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING group_id, group_name, description, image, creator_id, created_at
`

type CreateGroupParams struct {
	GroupID     []byte
	GroupName   string
	Description string
	Image       sql.NullString
	CreatorID   []byte
	CreatedAt   time.Time
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (*Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup,
		arg.GroupID,
		arg.GroupName,
		arg.Description,
		arg.Image,
		arg.CreatorID,
		arg.CreatedAt,
	)
	var i Group
	err := row.Scan(
		&i.GroupID,
		&i.GroupName,
		&i.Description,
		&i.Image,
		&i.CreatorID,
		&i.CreatedAt,
	)
	return &i, err
}

const createGroupEvent = `-- name: CreateGroupEvent :one
INSERT INTO group_events (event_id, group_id, creator_id, title, description, event_timestamp)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING event_id, creator_id, group_id, title, description, event_timestamp, created_at
`

type CreateGroupEventParams struct {
	EventID        []byte
	GroupID        []byte
	CreatorID      []byte
	Title          string
	Description    string
	EventTimestamp time.Time
}

func (q *Queries) CreateGroupEvent(ctx context.Context, arg CreateGroupEventParams) (*GroupEvent, error) {
	row := q.db.QueryRowContext(ctx, createGroupEvent,
		arg.EventID,
		arg.GroupID,
		arg.CreatorID,
		arg.Title,
		arg.Description,
		arg.EventTimestamp,
	)
	var i GroupEvent
	err := row.Scan(
		&i.EventID,
		&i.CreatorID,
		&i.GroupID,
		&i.Title,
		&i.Description,
		&i.EventTimestamp,
		&i.CreatedAt,
	)
	return &i, err
}

const createGroupMember = `-- name: CreateGroupMember :exec
INSERT INTO group_members (user_id, group_id, status, invited_by, created_at)
VALUES (?, ?, ?, NULL, ?)
`

type CreateGroupMemberParams struct {
	UserID    []byte
	GroupID   []byte
	Status    string
	CreatedAt sql.NullTime
}

func (q *Queries) CreateGroupMember(ctx context.Context, arg CreateGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, createGroupMember,
		arg.UserID,
		arg.GroupID,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const deleteDbGroup = `-- name: DeleteDbGroup :exec
DELETE FROM groups WHERE group_id = ?
`

func (q *Queries) DeleteDbGroup(ctx context.Context, groupID []byte) error {
	_, err := q.db.ExecContext(ctx, deleteDbGroup, groupID)
	return err
}

const getEventByID = `-- name: GetEventByID :one
SELECT event_id, creator_id, group_id, title, description, event_timestamp, created_at FROM group_events WHERE event_id = ?
`

func (q *Queries) GetEventByID(ctx context.Context, eventID []byte) (*GroupEvent, error) {
	row := q.db.QueryRowContext(ctx, getEventByID, eventID)
	var i GroupEvent
	err := row.Scan(
		&i.EventID,
		&i.CreatorID,
		&i.GroupID,
		&i.Title,
		&i.Description,
		&i.EventTimestamp,
		&i.CreatedAt,
	)
	return &i, err
}

const getEventGroupID = `-- name: GetEventGroupID :one
SELECT group_id FROM group_events WHERE event_id = ?
`

func (q *Queries) GetEventGroupID(ctx context.Context, eventID []byte) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getEventGroupID, eventID)
	var group_id []byte
	err := row.Scan(&group_id)
	return group_id, err
}

const getGroupById = `-- name: GetGroupById :one
SELECT
    g.group_id,
    g.group_name,
    g.description,
    g.image,
    g.creator_id,
    g.created_at,
    i.image_id as group_image_id,
    i.image_path as group_image_path,
    i.file_name as group_image_file_name
FROM groups g
LEFT JOIN images i ON g.image = i.image_id
WHERE g.group_id = ?
`

type GetGroupByIdRow struct {
	GroupID            []byte
	GroupName          string
	Description        string
	Image              sql.NullString
	CreatorID          []byte
	CreatedAt          time.Time
	GroupImageID       sql.NullString
	GroupImagePath     sql.NullString
	GroupImageFileName sql.NullString
}

func (q *Queries) GetGroupById(ctx context.Context, groupID []byte) (*GetGroupByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getGroupById, groupID)
	var i GetGroupByIdRow
	err := row.Scan(
		&i.GroupID,
		&i.GroupName,
		&i.Description,
		&i.Image,
		&i.CreatorID,
		&i.CreatedAt,
		&i.GroupImageID,
		&i.GroupImagePath,
		&i.GroupImageFileName,
	)
	return &i, err
}

const getGroupByName = `-- name: GetGroupByName :one
SELECT group_id, group_name, description, image, creator_id, created_at FROM groups WHERE group_name = ? LIMIT 1
`

func (q *Queries) GetGroupByName(ctx context.Context, groupName string) (*Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByName, groupName)
	var i Group
	err := row.Scan(
		&i.GroupID,
		&i.GroupName,
		&i.Description,
		&i.Image,
		&i.CreatorID,
		&i.CreatedAt,
	)
	return &i, err
}

const getGroupEvents = `-- name: GetGroupEvents :many
SELECT e.event_id, e.creator_id, e.group_id, e.title, e.description, e.event_timestamp, e.created_at,
    (SELECT COUNT(*) FROM group_rsvp r WHERE r.event_id=e.event_id AND r.status='going') as going_count,
    (SELECT COUNT(*) FROM group_rsvp r WHERE r.event_id=e.event_id AND r.status='not going') as not_going_count,
    (SELECT r.status FROM group_rsvp r WHERE r.event_id=e.event_id AND r.user_id=?) as user_rsvp
FROM group_events e
WHERE e.group_id = ?
ORDER BY e.event_timestamp ASC
`

type GetGroupEventsParams struct {
	UserID  []byte
	GroupID []byte
}

type GetGroupEventsRow struct {
	EventID        []byte
	CreatorID      []byte
	GroupID        []byte
	Title          string
	Description    string
	EventTimestamp time.Time
	CreatedAt      sql.NullTime
	GoingCount     int64
	NotGoingCount  int64
	UserRsvp       sql.NullString
}

func (q *Queries) GetGroupEvents(ctx context.Context, arg GetGroupEventsParams) ([]*GetGroupEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupEvents, arg.UserID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetGroupEventsRow
	for rows.Next() {
		var i GetGroupEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.CreatorID,
			&i.GroupID,
			&i.Title,
			&i.Description,
			&i.EventTimestamp,
			&i.CreatedAt,
			&i.GoingCount,
			&i.NotGoingCount,
			&i.UserRsvp,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupEventsWithRSVPs = `-- name: GetGroupEventsWithRSVPs :many
SELECT 
    ge.event_id,
    ge.title,
    ge.description,
    ge.event_timestamp,
    ge.created_at as event_created_at,
    gr.user_id as rsvp_user_id,
    gr.status as rsvp_status,
    gr.created_at as rsvp_created_at,
    u.first_name as rsvp_first_name,
    u.last_name as rsvp_last_name,
    u.avatar as rsvp_avatar
FROM group_events ge
LEFT JOIN group_rsvp gr ON ge.event_id = gr.event_id
LEFT JOIN users u ON gr.user_id = u.user_id
WHERE ge.group_id = ?
ORDER BY ge.event_timestamp DESC
`

type GetGroupEventsWithRSVPsRow struct {
	EventID        []byte
	Title          string
	Description    string
	EventTimestamp time.Time
	EventCreatedAt sql.NullTime
	RsvpUserID     []byte
	RsvpStatus     sql.NullString
	RsvpCreatedAt  sql.NullTime
	RsvpFirstName  sql.NullString
	RsvpLastName   sql.NullString
	RsvpAvatar     sql.NullString
}

func (q *Queries) GetGroupEventsWithRSVPs(ctx context.Context, groupID []byte) ([]*GetGroupEventsWithRSVPsRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupEventsWithRSVPs, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetGroupEventsWithRSVPsRow
	for rows.Next() {
		var i GetGroupEventsWithRSVPsRow
		if err := rows.Scan(
			&i.EventID,
			&i.Title,
			&i.Description,
			&i.EventTimestamp,
			&i.EventCreatedAt,
			&i.RsvpUserID,
			&i.RsvpStatus,
			&i.RsvpCreatedAt,
			&i.RsvpFirstName,
			&i.RsvpLastName,
			&i.RsvpAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupJoinRequests = `-- name: GetGroupJoinRequests :many
SELECT
    gm.user_id,
    gm.group_id,
    gm.status,
    gm.invited_by,
    gm.created_at,
    u.user_id AS m_user_id,
    u.first_name AS m_first_name,
    u.last_name AS m_last_name
FROM group_members gm
JOIN users u ON gm.user_id = u.user_id
WHERE group_id = ? AND status = 'requested'
`

type GetGroupJoinRequestsRow struct {
	UserID     []byte
	GroupID    []byte
	Status     string
	InvitedBy  []byte
	CreatedAt  sql.NullTime
	MUserID    []byte
	MFirstName string
	MLastName  string
}

func (q *Queries) GetGroupJoinRequests(ctx context.Context, groupID []byte) ([]*GetGroupJoinRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupJoinRequests, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetGroupJoinRequestsRow
	for rows.Next() {
		var i GetGroupJoinRequestsRow
		if err := rows.Scan(
			&i.UserID,
			&i.GroupID,
			&i.Status,
			&i.InvitedBy,
			&i.CreatedAt,
			&i.MUserID,
			&i.MFirstName,
			&i.MLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupMemberIDs = `-- name: GetGroupMemberIDs :many
SELECT user_id FROM group_members WHERE group_id = ? AND status = 'joined'
`

func (q *Queries) GetGroupMemberIDs(ctx context.Context, groupID []byte) ([][]byte, error) {
	rows, err := q.db.QueryContext(ctx, getGroupMemberIDs, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var user_id []byte
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupMembers = `-- name: GetGroupMembers :many
SELECT 
    gm.user_id,
    gm.status,
    u.first_name,
    u.last_name,
    u.avatar
FROM group_members gm
JOIN users u ON gm.user_id = u.user_id
WHERE gm.group_id = ? AND gm.status = 'joined'
`

type GetGroupMembersRow struct {
	UserID    []byte
	Status    string
	FirstName string
	LastName  string
	Avatar    sql.NullString
}

func (q *Queries) GetGroupMembers(ctx context.Context, groupID []byte) ([]*GetGroupMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetGroupMembersRow
	for rows.Next() {
		var i GetGroupMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Status,
			&i.FirstName,
			&i.LastName,
			&i.Avatar,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupMembersWithRequests = `-- name: GetGroupMembersWithRequests :many
SELECT user_id, group_id, status, invited_by, created_at FROM group_members WHERE group_id = ?
`

func (q *Queries) GetGroupMembersWithRequests(ctx context.Context, groupID []byte) ([]*GroupMember, error) {
	rows, err := q.db.QueryContext(ctx, getGroupMembersWithRequests, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GroupMember
	for rows.Next() {
		var i GroupMember
		if err := rows.Scan(
			&i.UserID,
			&i.GroupID,
			&i.Status,
			&i.InvitedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupsWithMemberCount = `-- name: GetGroupsWithMemberCount :many
SELECT
    g.group_id,
    g.group_name,
    g.description,
    g.image,
    g.creator_id,
    g.created_at,
    i.image_id as group_image,
    i.image_path as group_image_path,
    i.file_name as group_image_file_name,
    COUNT(gm.user_id) as member_count
FROM groups g
LEFT JOIN group_members gm ON g.group_id = gm.group_id AND gm.status = 'joined'
LEFT JOIN images i ON g.image = i.image_id
GROUP BY g.group_id
ORDER BY g.created_at DESC
`

type GetGroupsWithMemberCountRow struct {
	GroupID            []byte
	GroupName          string
	Description        string
	Image              sql.NullString
	CreatorID          []byte
	CreatedAt          time.Time
	GroupImage         sql.NullString
	GroupImagePath     sql.NullString
	GroupImageFileName sql.NullString
	MemberCount        int64
}

func (q *Queries) GetGroupsWithMemberCount(ctx context.Context) ([]*GetGroupsWithMemberCountRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupsWithMemberCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetGroupsWithMemberCountRow
	for rows.Next() {
		var i GetGroupsWithMemberCountRow
		if err := rows.Scan(
			&i.GroupID,
			&i.GroupName,
			&i.Description,
			&i.Image,
			&i.CreatorID,
			&i.CreatedAt,
			&i.GroupImage,
			&i.GroupImagePath,
			&i.GroupImageFileName,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const inviteGroupMembers = `-- name: InviteGroupMembers :exec
INSERT INTO group_members (user_id, group_id, status, invited_by) VALUES (?, ?, ?, ?)
`

type InviteGroupMembersParams struct {
	UserID    []byte
	GroupID   []byte
	Status    string
	InvitedBy []byte
}

func (q *Queries) InviteGroupMembers(ctx context.Context, arg InviteGroupMembersParams) error {
	_, err := q.db.ExecContext(ctx, inviteGroupMembers,
		arg.UserID,
		arg.GroupID,
		arg.Status,
		arg.InvitedBy,
	)
	return err
}

const isGroupMember = `-- name: IsGroupMember :one
SELECT user_id, group_id, status, invited_by, created_at FROM group_members
WHERE user_id = ? AND group_id = ? LIMIT 1
`

type IsGroupMemberParams struct {
	UserID  []byte
	GroupID []byte
}

func (q *Queries) IsGroupMember(ctx context.Context, arg IsGroupMemberParams) (*GroupMember, error) {
	row := q.db.QueryRowContext(ctx, isGroupMember, arg.UserID, arg.GroupID)
	var i GroupMember
	err := row.Scan(
		&i.UserID,
		&i.GroupID,
		&i.Status,
		&i.InvitedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const removeUserFromGroup = `-- name: RemoveUserFromGroup :exec
DELETE FROM group_members WHERE user_id = ? AND group_id = ?
`

type RemoveUserFromGroupParams struct {
	UserID  []byte
	GroupID []byte
}

func (q *Queries) RemoveUserFromGroup(ctx context.Context, arg RemoveUserFromGroupParams) error {
	_, err := q.db.ExecContext(ctx, removeUserFromGroup, arg.UserID, arg.GroupID)
	return err
}

const updateDbGroup = `-- name: UpdateDbGroup :one
UPDATE groups SET group_name = ?, description = ?, image = ?
WHERE group_id = ? AND creator_id = ? RETURNING group_id, group_name, description, image, creator_id, created_at
`

type UpdateDbGroupParams struct {
	GroupName   string
	Description string
	Image       sql.NullString
	GroupID     []byte
	CreatorID   []byte
}

func (q *Queries) UpdateDbGroup(ctx context.Context, arg UpdateDbGroupParams) (*Group, error) {
	row := q.db.QueryRowContext(ctx, updateDbGroup,
		arg.GroupName,
		arg.Description,
		arg.Image,
		arg.GroupID,
		arg.CreatorID,
	)
	var i Group
	err := row.Scan(
		&i.GroupID,
		&i.GroupName,
		&i.Description,
		&i.Image,
		&i.CreatorID,
		&i.CreatedAt,
	)
	return &i, err
}

const updateGroupMemberStatus = `-- name: UpdateGroupMemberStatus :exec
UPDATE group_members SET status = ? WHERE user_id = ?
`

type UpdateGroupMemberStatusParams struct {
	Status string
	UserID []byte
}

func (q *Queries) UpdateGroupMemberStatus(ctx context.Context, arg UpdateGroupMemberStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateGroupMemberStatus, arg.Status, arg.UserID)
	return err
}

const upsertRSVP = `-- name: UpsertRSVP :exec
INSERT INTO group_rsvp (event_id, user_id, status) VALUES (?, ?, ?)
ON CONFLICT(event_id, user_id) DO UPDATE SET status = excluded.status
`

type UpsertRSVPParams struct {
	EventID string
	UserID  []byte
	Status  sql.NullString
}

func (q *Queries) UpsertRSVP(ctx context.Context, arg UpsertRSVPParams) error {
	_, err := q.db.ExecContext(ctx, upsertRSVP, arg.EventID, arg.UserID, arg.Status)
	return err
}
