// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package db_groups

import (
	"context"
	"database/sql"
	"time"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (group_id, group_name, description, image, creator_id, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING group_id, group_name, description, image, creator_id, created_at
`

type CreateGroupParams struct {
	GroupID     []byte
	GroupName   string
	Description string
	Image       sql.NullString
	CreatorID   []byte
	CreatedAt   time.Time
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup,
		arg.GroupID,
		arg.GroupName,
		arg.Description,
		arg.Image,
		arg.CreatorID,
		arg.CreatedAt,
	)
	var i Group
	err := row.Scan(
		&i.GroupID,
		&i.GroupName,
		&i.Description,
		&i.Image,
		&i.CreatorID,
		&i.CreatedAt,
	)
	return i, err
}

const createGroupMember = `-- name: CreateGroupMember :exec
INSERT INTO group_members (user_id, group_id, status, invited_by, created_at)
VALUES (?, ?, ?, NULL, ?)
`

type CreateGroupMemberParams struct {
	UserID    []byte
	GroupID   []byte
	Status    string
	CreatedAt sql.NullTime
}

func (q *Queries) CreateGroupMember(ctx context.Context, arg CreateGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, createGroupMember,
		arg.UserID,
		arg.GroupID,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const getGroupById = `-- name: GetGroupById :one
SELECT group_id, group_name, description, image, creator_id, created_at FROM groups WHERE group_id = ?
`

func (q *Queries) GetGroupById(ctx context.Context, groupID []byte) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupById, groupID)
	var i Group
	err := row.Scan(
		&i.GroupID,
		&i.GroupName,
		&i.Description,
		&i.Image,
		&i.CreatorID,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupByName = `-- name: GetGroupByName :one
SELECT group_name FROM groups WHERE group_name = ? LIMIT 1
`

func (q *Queries) GetGroupByName(ctx context.Context, groupName string) (string, error) {
	row := q.db.QueryRowContext(ctx, getGroupByName, groupName)
	var group_name string
	err := row.Scan(&group_name)
	return group_name, err
}

const getGroupEventsWithRSVPs = `-- name: GetGroupEventsWithRSVPs :many
SELECT 
    ge.event_id,
    ge.title,
    ge.description,
    ge.event_timestamp,
    ge.created_at as event_created_at,
    gr.user_id as rsvp_user_id,
    gr.status as rsvp_status,
    gr.created_at as rsvp_created_at,
    u.first_name as rsvp_first_name,
    u.last_name as rsvp_last_name,
    u.avatar as rsvp_avatar
FROM group_events ge
LEFT JOIN group_rsvp gr ON ge.event_id = gr.event_id
LEFT JOIN users u ON gr.user_id = u.user_id
WHERE ge.group_id = ?
ORDER BY ge.event_timestamp DESC
`

type GetGroupEventsWithRSVPsRow struct {
	EventID        []byte
	Title          string
	Description    string
	EventTimestamp time.Time
	EventCreatedAt sql.NullTime
	RsvpUserID     []byte
	RsvpStatus     sql.NullString
	RsvpCreatedAt  sql.NullTime
	RsvpFirstName  sql.NullString
	RsvpLastName   sql.NullString
	RsvpAvatar     sql.NullString
}

func (q *Queries) GetGroupEventsWithRSVPs(ctx context.Context, groupID []byte) ([]GetGroupEventsWithRSVPsRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupEventsWithRSVPs, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupEventsWithRSVPsRow
	for rows.Next() {
		var i GetGroupEventsWithRSVPsRow
		if err := rows.Scan(
			&i.EventID,
			&i.Title,
			&i.Description,
			&i.EventTimestamp,
			&i.EventCreatedAt,
			&i.RsvpUserID,
			&i.RsvpStatus,
			&i.RsvpCreatedAt,
			&i.RsvpFirstName,
			&i.RsvpLastName,
			&i.RsvpAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupMembers = `-- name: GetGroupMembers :many
SELECT 
    gm.user_id,
    gm.status,
    u.first_name,
    u.last_name,
    u.avatar
FROM group_members gm
JOIN users u ON gm.user_id = u.user_id
WHERE gm.group_id = ? AND gm.status = 'joined'
`

type GetGroupMembersRow struct {
	UserID    []byte
	Status    string
	FirstName string
	LastName  string
	Avatar    sql.NullString
}

func (q *Queries) GetGroupMembers(ctx context.Context, groupID []byte) ([]GetGroupMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupMembersRow
	for rows.Next() {
		var i GetGroupMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Status,
			&i.FirstName,
			&i.LastName,
			&i.Avatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupMembersWithRequests = `-- name: GetGroupMembersWithRequests :many
SELECT user_id, group_id, status, invited_by, created_at FROM group_members WHERE group_id = ?
`

func (q *Queries) GetGroupMembersWithRequests(ctx context.Context, groupID []byte) ([]GroupMember, error) {
	rows, err := q.db.QueryContext(ctx, getGroupMembersWithRequests, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupMember
	for rows.Next() {
		var i GroupMember
		if err := rows.Scan(
			&i.UserID,
			&i.GroupID,
			&i.Status,
			&i.InvitedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupsWithMemberCount = `-- name: GetGroupsWithMemberCount :many
SELECT
    g.group_id,
    g.group_name,
    g.description,
    g.image,
    g.creator_id,
    g.created_at,
    COUNT(gm.user_id) as member_count
FROM groups g
LEFT JOIN group_members gm ON g.group_id = gm.group_id AND gm.status = 'joined'
GROUP BY g.group_id
ORDER BY g.created_at DESC
`

type GetGroupsWithMemberCountRow struct {
	GroupID     []byte
	GroupName   string
	Description string
	Image       sql.NullString
	CreatorID   []byte
	CreatedAt   time.Time
	MemberCount int64
}

func (q *Queries) GetGroupsWithMemberCount(ctx context.Context) ([]GetGroupsWithMemberCountRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupsWithMemberCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupsWithMemberCountRow
	for rows.Next() {
		var i GetGroupsWithMemberCountRow
		if err := rows.Scan(
			&i.GroupID,
			&i.GroupName,
			&i.Description,
			&i.Image,
			&i.CreatorID,
			&i.CreatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const inviteGroupMembers = `-- name: InviteGroupMembers :exec
INSERT INTO group_members (user_id, group_id, status, invited_by) VALUES (?, ?, ?, ?)
`

type InviteGroupMembersParams struct {
	UserID    []byte
	GroupID   []byte
	Status    string
	InvitedBy []byte
}

func (q *Queries) InviteGroupMembers(ctx context.Context, arg InviteGroupMembersParams) error {
	_, err := q.db.ExecContext(ctx, inviteGroupMembers,
		arg.UserID,
		arg.GroupID,
		arg.Status,
		arg.InvitedBy,
	)
	return err
}

const isGroupMember = `-- name: IsGroupMember :one
SELECT user_id, group_id, status, invited_by, created_at FROM group_members
WHERE user_id = ? AND group_id = ? LIMIT 1
`

type IsGroupMemberParams struct {
	UserID  []byte
	GroupID []byte
}

func (q *Queries) IsGroupMember(ctx context.Context, arg IsGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRowContext(ctx, isGroupMember, arg.UserID, arg.GroupID)
	var i GroupMember
	err := row.Scan(
		&i.UserID,
		&i.GroupID,
		&i.Status,
		&i.InvitedBy,
		&i.CreatedAt,
	)
	return i, err
}

const removeUserFromGroup = `-- name: RemoveUserFromGroup :exec
DELETE FROM group_members WHERE user_id = ? AND group_id = ?
`

type RemoveUserFromGroupParams struct {
	UserID  []byte
	GroupID []byte
}

func (q *Queries) RemoveUserFromGroup(ctx context.Context, arg RemoveUserFromGroupParams) error {
	_, err := q.db.ExecContext(ctx, removeUserFromGroup, arg.UserID, arg.GroupID)
	return err
}

const updateGroupMemberStatus = `-- name: UpdateGroupMemberStatus :exec
UPDATE group_members SET status = ? WHERE user_id = ?
`

type UpdateGroupMemberStatusParams struct {
	Status string
	UserID []byte
}

func (q *Queries) UpdateGroupMemberStatus(ctx context.Context, arg UpdateGroupMemberStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateGroupMemberStatus, arg.Status, arg.UserID)
	return err
}
