// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_groups

import (
	"database/sql"
	"time"
)

type Group struct {
	GroupID     []byte
	GroupName   string
	Description string
	Image       sql.NullString
	CreatorID   []byte
	CreatedAt   time.Time
}

type GroupEvent struct {
	EventID        []byte
	CreatorID      []byte
	GroupID        []byte
	Title          string
	Description    string
	EventTimestamp time.Time
	CreatedAt      sql.NullTime
}

type GroupMember struct {
	UserID    []byte
	GroupID   []byte
	Status    string
	InvitedBy []byte
	CreatedAt sql.NullTime
}

type GroupRsvp struct {
	EventID   string
	UserID    []byte
	Status    sql.NullString
	CreatedAt sql.NullTime
}

type Image struct {
	ImageID   string
	PosterID  []byte
	ImagePath string
	FileName  string
	CreatedAt sql.NullTime
	ExpiresAt sql.NullTime
}

type User struct {
	UserID       []byte
	Email        string
	PasswordHash []byte
	FirstName    string
	LastName     string
	Dob          string
	Avatar       sql.NullString
	Nickname     sql.NullString
	AboutMe      sql.NullString
	IsPublic     bool
	CreatedAt    sql.NullTime
}
