// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_groups

import (
	"database/sql"
	"time"
)

type Group struct {
	GroupID     []byte
	GroupName   string
	Description string
	Image       sql.NullString
	CreatorID   []byte
	CreatedAt   time.Time
}

type GroupEvent struct {
	EventID        []byte
	CreatorID      []byte
	GroupID        []byte
	Title          string
	Description    string
	EventTimestamp time.Time
	CreatedAt      sql.NullTime
}

type GroupMember struct {
	UserID    []byte
	GroupID   []byte
	Status    string
	InvitedBy []byte
	CreatedAt sql.NullTime
}
