// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requests.sql

package db_requests

import (
	"context"
)

const acceptFollowRequest = `-- name: AcceptFollowRequest :exec
UPDATE follow_requests SET status = 'accepted' WHERE id = ?
`

func (q *Queries) AcceptFollowRequest(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, acceptFollowRequest, id)
	return err
}

const createFollowRequest = `-- name: CreateFollowRequest :exec
INSERT INTO follow_requests (follower_id, followee_id) VALUES (?, ?)
`

type CreateFollowRequestParams struct {
	FollowerID []byte
	FolloweeID []byte
}

func (q *Queries) CreateFollowRequest(ctx context.Context, arg CreateFollowRequestParams) error {
	_, err := q.db.ExecContext(ctx, createFollowRequest, arg.FollowerID, arg.FolloweeID)
	return err
}

const deleteFollowRequest = `-- name: DeleteFollowRequest :exec
DELETE FROM follow_requests WHERE id = ?
`

func (q *Queries) DeleteFollowRequest(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFollowRequest, id)
	return err
}

const getFollowRequest = `-- name: GetFollowRequest :one
SELECT id, follower_id, followee_id, status, created_at, responded_at FROM follow_requests WHERE follower_id = ? AND followee_id = ?
`

type GetFollowRequestParams struct {
	FollowerID []byte
	FolloweeID []byte
}

func (q *Queries) GetFollowRequest(ctx context.Context, arg GetFollowRequestParams) (FollowRequest, error) {
	row := q.db.QueryRowContext(ctx, getFollowRequest, arg.FollowerID, arg.FolloweeID)
	var i FollowRequest
	err := row.Scan(
		&i.ID,
		&i.FollowerID,
		&i.FolloweeID,
		&i.Status,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}

const getFollowRequestByID = `-- name: GetFollowRequestByID :one
SELECT id, follower_id, followee_id, status, created_at, responded_at FROM follow_requests WHERE id = ? AND followee_id = ? AND status = 'pending'
`

type GetFollowRequestByIDParams struct {
	ID         int64
	FolloweeID []byte
}

func (q *Queries) GetFollowRequestByID(ctx context.Context, arg GetFollowRequestByIDParams) (FollowRequest, error) {
	row := q.db.QueryRowContext(ctx, getFollowRequestByID, arg.ID, arg.FolloweeID)
	var i FollowRequest
	err := row.Scan(
		&i.ID,
		&i.FollowerID,
		&i.FolloweeID,
		&i.Status,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}

const getFollowRequests = `-- name: GetFollowRequests :many
SELECT id, follower_id, followee_id, status, created_at, responded_at FROM follow_requests WHERE followee_id = ? AND status = 'pending'
`

func (q *Queries) GetFollowRequests(ctx context.Context, followeeID []byte) ([]FollowRequest, error) {
	rows, err := q.db.QueryContext(ctx, getFollowRequests, followeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FollowRequest
	for rows.Next() {
		var i FollowRequest
		if err := rows.Scan(
			&i.ID,
			&i.FollowerID,
			&i.FolloweeID,
			&i.Status,
			&i.CreatedAt,
			&i.RespondedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
