// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_notifications

import (
	"database/sql"
	"time"
)

type Group struct {
	GroupID     []byte
	GroupName   string
	Description string
	Image       sql.NullString
	CreatorID   []byte
	CreatedAt   time.Time
}

type GroupEvent struct {
	EventID        []byte
	CreatorID      []byte
	GroupID        []byte
	Title          string
	Description    string
	EventTimestamp time.Time
	CreatedAt      sql.NullTime
}

type Notification struct {
	NotifID    string
	ReceiverID []byte
	Type       string
	IsSeen     sql.NullBool
	FromID     []byte
	GroupID    []byte
	EventID    []byte
	CreatedAt  sql.NullTime
}

type User struct {
	UserID       []byte
	Email        string
	PasswordHash []byte
	FirstName    string
	LastName     string
	Dob          string
	Avatar       sql.NullString
	Nickname     sql.NullString
	AboutMe      sql.NullString
	IsPublic     bool
	CreatedAt    sql.NullTime
}
