// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db_notifications

import (
	"context"
	"database/sql"
)

const createNotification = `-- name: CreateNotification :exec
INSERT INTO notifications (notif_id, receiver_id, type, from_id, group_id, event_id)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateNotificationParams struct {
	NotifID    string
	ReceiverID []byte
	Type       string
	FromID     []byte
	GroupID    []byte
	EventID    []byte
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.ExecContext(ctx, createNotification,
		arg.NotifID,
		arg.ReceiverID,
		arg.Type,
		arg.FromID,
		arg.GroupID,
		arg.EventID,
	)
	return err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT notif_id, receiver_id, type, is_seen, from_id, group_id, event_id, created_at FROM notifications WHERE notif_id = ? AND receiver_id = ?
`

type GetNotificationByIDParams struct {
	NotifID    string
	ReceiverID []byte
}

func (q *Queries) GetNotificationByID(ctx context.Context, arg GetNotificationByIDParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, getNotificationByID, arg.NotifID, arg.ReceiverID)
	var i Notification
	err := row.Scan(
		&i.NotifID,
		&i.ReceiverID,
		&i.Type,
		&i.IsSeen,
		&i.FromID,
		&i.GroupID,
		&i.EventID,
		&i.CreatedAt,
	)
	return i, err
}

const getNotifications = `-- name: GetNotifications :many
SELECT n.notif_id, n.receiver_id, n.type, n.is_seen, n.from_id, n.group_id, n.event_id, n.created_at,
       u.first_name as from_first_name,
       u.last_name as from_last_name,
       g.group_name,
       e.title as event_title
FROM notifications n
LEFT JOIN users u ON n.from_id = u.user_id
LEFT JOIN groups g ON n.group_id = g.group_id
LEFT JOIN group_events e ON n.event_id = e.event_id
WHERE n.receiver_id = ?
ORDER BY n.created_at DESC
LIMIT ? OFFSET ?
`

type GetNotificationsParams struct {
	ReceiverID []byte
	Limit      int64
	Offset     int64
}

type GetNotificationsRow struct {
	NotifID       string
	ReceiverID    []byte
	Type          string
	IsSeen        sql.NullBool
	FromID        []byte
	GroupID       []byte
	EventID       []byte
	CreatedAt     sql.NullTime
	FromFirstName sql.NullString
	FromLastName  sql.NullString
	GroupName     sql.NullString
	EventTitle    sql.NullString
}

func (q *Queries) GetNotifications(ctx context.Context, arg GetNotificationsParams) ([]GetNotificationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getNotifications, arg.ReceiverID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNotificationsRow
	for rows.Next() {
		var i GetNotificationsRow
		if err := rows.Scan(
			&i.NotifID,
			&i.ReceiverID,
			&i.Type,
			&i.IsSeen,
			&i.FromID,
			&i.GroupID,
			&i.EventID,
			&i.CreatedAt,
			&i.FromFirstName,
			&i.FromLastName,
			&i.GroupName,
			&i.EventTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadCount = `-- name: GetUnreadCount :one
SELECT COUNT(*) FROM notifications WHERE receiver_id = ? AND is_seen = 0
`

func (q *Queries) GetUnreadCount(ctx context.Context, receiverID []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUnreadCount, receiverID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const markAllAsRead = `-- name: MarkAllAsRead :exec
UPDATE notifications SET is_seen = 1 WHERE receiver_id = ?
`

func (q *Queries) MarkAllAsRead(ctx context.Context, receiverID []byte) error {
	_, err := q.db.ExecContext(ctx, markAllAsRead, receiverID)
	return err
}

const markAsRead = `-- name: MarkAsRead :exec
UPDATE notifications SET is_seen = 1 WHERE notif_id = ? AND receiver_id = ?
`

type MarkAsReadParams struct {
	NotifID    string
	ReceiverID []byte
}

func (q *Queries) MarkAsRead(ctx context.Context, arg MarkAsReadParams) error {
	_, err := q.db.ExecContext(ctx, markAsRead, arg.NotifID, arg.ReceiverID)
	return err
}
