// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db_notifications

import (
	"context"
	"database/sql"
)

const countUnseenNotifications = `-- name: CountUnseenNotifications :one
SELECT COUNT(*) FROM notifications
WHERE receiver_id = ? AND is_seen = 0
`

func (q *Queries) CountUnseenNotifications(ctx context.Context, receiverID []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnseenNotifications, receiverID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (notif_id, receiver_id, type, from_id, group_id, event_id, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING notif_id, receiver_id, type, is_seen, from_id, group_id, event_id, created_at
`

type CreateNotificationParams struct {
	NotifID    string
	ReceiverID []byte
	Type       string
	FromID     []byte
	GroupID    []byte
	EventID    []byte
	CreatedAt  sql.NullTime
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.NotifID,
		arg.ReceiverID,
		arg.Type,
		arg.FromID,
		arg.GroupID,
		arg.EventID,
		arg.CreatedAt,
	)
	var i Notification
	err := row.Scan(
		&i.NotifID,
		&i.ReceiverID,
		&i.Type,
		&i.IsSeen,
		&i.FromID,
		&i.GroupID,
		&i.EventID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCommentNotificationByReceiverAndType = `-- name: DeleteCommentNotificationByReceiverAndType :exec
DELETE FROM notifications
WHERE receiver_id = ? AND from_id = ? AND type = ?
`

type DeleteCommentNotificationByReceiverAndTypeParams struct {
	ReceiverID []byte
	FromID     []byte
	Type       string
}

func (q *Queries) DeleteCommentNotificationByReceiverAndType(ctx context.Context, arg DeleteCommentNotificationByReceiverAndTypeParams) error {
	_, err := q.db.ExecContext(ctx, deleteCommentNotificationByReceiverAndType, arg.ReceiverID, arg.FromID, arg.Type)
	return err
}

const deleteCommentReactionNotification = `-- name: DeleteCommentReactionNotification :exec
DELETE FROM notifications
WHERE receiver_id = ? AND from_id = ? AND type = 'comment_reaction'
`

type DeleteCommentReactionNotificationParams struct {
	ReceiverID []byte
	FromID     []byte
}

func (q *Queries) DeleteCommentReactionNotification(ctx context.Context, arg DeleteCommentReactionNotificationParams) error {
	_, err := q.db.ExecContext(ctx, deleteCommentReactionNotification, arg.ReceiverID, arg.FromID)
	return err
}

const deleteFollowRequestNotification = `-- name: DeleteFollowRequestNotification :exec
DELETE FROM notifications 
WHERE receiver_id = ? AND from_id = ? AND type = 'follow_request'
`

type DeleteFollowRequestNotificationParams struct {
	ReceiverID []byte
	FromID     []byte
}

func (q *Queries) DeleteFollowRequestNotification(ctx context.Context, arg DeleteFollowRequestNotificationParams) error {
	_, err := q.db.ExecContext(ctx, deleteFollowRequestNotification, arg.ReceiverID, arg.FromID)
	return err
}

const deleteGroupRequestNotification = `-- name: DeleteGroupRequestNotification :exec
DELETE FROM notifications
WHERE receiver_id = ? AND from_id = ? AND group_id = ? AND type = 'group_request'
`

type DeleteGroupRequestNotificationParams struct {
	ReceiverID []byte
	FromID     []byte
	GroupID    []byte
}

func (q *Queries) DeleteGroupRequestNotification(ctx context.Context, arg DeleteGroupRequestNotificationParams) error {
	_, err := q.db.ExecContext(ctx, deleteGroupRequestNotification, arg.ReceiverID, arg.FromID, arg.GroupID)
	return err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications WHERE notif_id = ?
`

func (q *Queries) DeleteNotification(ctx context.Context, notifID string) error {
	_, err := q.db.ExecContext(ctx, deleteNotification, notifID)
	return err
}

const deleteNotificationsByReceiverId = `-- name: DeleteNotificationsByReceiverId :exec
DELETE FROM notifications WHERE receiver_id = ?
`

func (q *Queries) DeleteNotificationsByReceiverId(ctx context.Context, receiverID []byte) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationsByReceiverId, receiverID)
	return err
}

const deletePostReactionNotification = `-- name: DeletePostReactionNotification :exec
DELETE FROM notifications
WHERE receiver_id = ? AND from_id = ? AND type = 'post_reaction'
`

type DeletePostReactionNotificationParams struct {
	ReceiverID []byte
	FromID     []byte
}

func (q *Queries) DeletePostReactionNotification(ctx context.Context, arg DeletePostReactionNotificationParams) error {
	_, err := q.db.ExecContext(ctx, deletePostReactionNotification, arg.ReceiverID, arg.FromID)
	return err
}

const getLastCommentReactionNotification = `-- name: GetLastCommentReactionNotification :one
SELECT created_at FROM notifications
WHERE receiver_id = ? AND from_id = ? AND type = 'comment_reaction'
ORDER BY created_at DESC
LIMIT 1
`

type GetLastCommentReactionNotificationParams struct {
	ReceiverID []byte
	FromID     []byte
}

func (q *Queries) GetLastCommentReactionNotification(ctx context.Context, arg GetLastCommentReactionNotificationParams) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, getLastCommentReactionNotification, arg.ReceiverID, arg.FromID)
	var created_at sql.NullTime
	err := row.Scan(&created_at)
	return created_at, err
}

const getLastFollowAcceptedNotification = `-- name: GetLastFollowAcceptedNotification :one
SELECT created_at FROM notifications
WHERE receiver_id = ? AND from_id = ? AND type = 'follow_accepted'
ORDER BY created_at DESC
LIMIT 1
`

type GetLastFollowAcceptedNotificationParams struct {
	ReceiverID []byte
	FromID     []byte
}

func (q *Queries) GetLastFollowAcceptedNotification(ctx context.Context, arg GetLastFollowAcceptedNotificationParams) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, getLastFollowAcceptedNotification, arg.ReceiverID, arg.FromID)
	var created_at sql.NullTime
	err := row.Scan(&created_at)
	return created_at, err
}

const getLastFollowRequestNotification = `-- name: GetLastFollowRequestNotification :one
SELECT created_at FROM notifications
WHERE receiver_id = ? AND from_id = ? AND type = 'follow_request'
ORDER BY created_at DESC
LIMIT 1
`

type GetLastFollowRequestNotificationParams struct {
	ReceiverID []byte
	FromID     []byte
}

func (q *Queries) GetLastFollowRequestNotification(ctx context.Context, arg GetLastFollowRequestNotificationParams) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, getLastFollowRequestNotification, arg.ReceiverID, arg.FromID)
	var created_at sql.NullTime
	err := row.Scan(&created_at)
	return created_at, err
}

const getLastGroupJoinApprovedNotification = `-- name: GetLastGroupJoinApprovedNotification :one
SELECT created_at FROM notifications
WHERE receiver_id = ? AND from_id = ? AND type = 'group_join_approved'
ORDER BY created_at DESC
LIMIT 1
`

type GetLastGroupJoinApprovedNotificationParams struct {
	ReceiverID []byte
	FromID     []byte
}

func (q *Queries) GetLastGroupJoinApprovedNotification(ctx context.Context, arg GetLastGroupJoinApprovedNotificationParams) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, getLastGroupJoinApprovedNotification, arg.ReceiverID, arg.FromID)
	var created_at sql.NullTime
	err := row.Scan(&created_at)
	return created_at, err
}

const getLastGroupRequestNotification = `-- name: GetLastGroupRequestNotification :one
SELECT created_at FROM notifications
WHERE receiver_id = ? AND from_id = ? AND type = 'group_request'
ORDER BY created_at DESC
LIMIT 1
`

type GetLastGroupRequestNotificationParams struct {
	ReceiverID []byte
	FromID     []byte
}

func (q *Queries) GetLastGroupRequestNotification(ctx context.Context, arg GetLastGroupRequestNotificationParams) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, getLastGroupRequestNotification, arg.ReceiverID, arg.FromID)
	var created_at sql.NullTime
	err := row.Scan(&created_at)
	return created_at, err
}

const getLastMessageNotification = `-- name: GetLastMessageNotification :one
SELECT created_at FROM notifications
WHERE receiver_id = ? AND from_id = ? AND type = 'message'
ORDER BY created_at DESC
LIMIT 1
`

type GetLastMessageNotificationParams struct {
	ReceiverID []byte
	FromID     []byte
}

func (q *Queries) GetLastMessageNotification(ctx context.Context, arg GetLastMessageNotificationParams) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, getLastMessageNotification, arg.ReceiverID, arg.FromID)
	var created_at sql.NullTime
	err := row.Scan(&created_at)
	return created_at, err
}

const getLastPostReactionNotification = `-- name: GetLastPostReactionNotification :one
SELECT created_at FROM notifications
WHERE receiver_id = ? AND from_id = ? AND type = 'post_reaction'
ORDER BY created_at DESC
LIMIT 1
`

type GetLastPostReactionNotificationParams struct {
	ReceiverID []byte
	FromID     []byte
}

func (q *Queries) GetLastPostReactionNotification(ctx context.Context, arg GetLastPostReactionNotificationParams) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, getLastPostReactionNotification, arg.ReceiverID, arg.FromID)
	var created_at sql.NullTime
	err := row.Scan(&created_at)
	return created_at, err
}

const getNotificationById = `-- name: GetNotificationById :one
SELECT notif_id, receiver_id, type, is_seen, from_id, group_id, event_id, created_at FROM notifications WHERE notif_id = ? LIMIT 1
`

func (q *Queries) GetNotificationById(ctx context.Context, notifID string) (Notification, error) {
	row := q.db.QueryRowContext(ctx, getNotificationById, notifID)
	var i Notification
	err := row.Scan(
		&i.NotifID,
		&i.ReceiverID,
		&i.Type,
		&i.IsSeen,
		&i.FromID,
		&i.GroupID,
		&i.EventID,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationWithUserDetails = `-- name: GetNotificationWithUserDetails :many
SELECT
    n.notif_id,
    n.receiver_id,
    n.type,
    n.is_seen,
    n.from_id,
    n.group_id,
    n.event_id,
    n.created_at,
    u.first_name as from_first_name,
    u.last_name as from_last_name,
    u.avatar as from_avatar,
    u.nickname as from_nickname
FROM notifications n
JOIN users u ON n.from_id = u.user_id
WHERE n.receiver_id = ?
ORDER BY n.created_at DESC
`

type GetNotificationWithUserDetailsRow struct {
	NotifID       string
	ReceiverID    []byte
	Type          string
	IsSeen        sql.NullBool
	FromID        []byte
	GroupID       []byte
	EventID       []byte
	CreatedAt     sql.NullTime
	FromFirstName string
	FromLastName  string
	FromAvatar    sql.NullString
	FromNickname  sql.NullString
}

func (q *Queries) GetNotificationWithUserDetails(ctx context.Context, receiverID []byte) ([]GetNotificationWithUserDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationWithUserDetails, receiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNotificationWithUserDetailsRow
	for rows.Next() {
		var i GetNotificationWithUserDetailsRow
		if err := rows.Scan(
			&i.NotifID,
			&i.ReceiverID,
			&i.Type,
			&i.IsSeen,
			&i.FromID,
			&i.GroupID,
			&i.EventID,
			&i.CreatedAt,
			&i.FromFirstName,
			&i.FromLastName,
			&i.FromAvatar,
			&i.FromNickname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationsByReceiverId = `-- name: GetNotificationsByReceiverId :many
SELECT notif_id, receiver_id, type, is_seen, from_id, group_id, event_id, created_at FROM notifications
WHERE receiver_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetNotificationsByReceiverId(ctx context.Context, receiverID []byte) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationsByReceiverId, receiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.NotifID,
			&i.ReceiverID,
			&i.Type,
			&i.IsSeen,
			&i.FromID,
			&i.GroupID,
			&i.EventID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationsByType = `-- name: GetNotificationsByType :many
SELECT notif_id, receiver_id, type, is_seen, from_id, group_id, event_id, created_at FROM notifications
WHERE receiver_id = ? AND type = ?
ORDER BY created_at DESC
`

type GetNotificationsByTypeParams struct {
	ReceiverID []byte
	Type       string
}

func (q *Queries) GetNotificationsByType(ctx context.Context, arg GetNotificationsByTypeParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationsByType, arg.ReceiverID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.NotifID,
			&i.ReceiverID,
			&i.Type,
			&i.IsSeen,
			&i.FromID,
			&i.GroupID,
			&i.EventID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnseenNotificationsByReceiverId = `-- name: GetUnseenNotificationsByReceiverId :many
SELECT notif_id, receiver_id, type, is_seen, from_id, group_id, event_id, created_at FROM notifications
WHERE receiver_id = ? AND is_seen = 0
ORDER BY created_at DESC
`

func (q *Queries) GetUnseenNotificationsByReceiverId(ctx context.Context, receiverID []byte) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getUnseenNotificationsByReceiverId, receiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.NotifID,
			&i.ReceiverID,
			&i.Type,
			&i.IsSeen,
			&i.FromID,
			&i.GroupID,
			&i.EventID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnseenNotificationsWithUserDetails = `-- name: GetUnseenNotificationsWithUserDetails :many
SELECT
    n.notif_id,
    n.receiver_id,
    n.type,
    n.is_seen,
    n.from_id,
    n.group_id,
    n.event_id,
    n.created_at,
    u.first_name as from_first_name,
    u.last_name as from_last_name,
    u.avatar as from_avatar,
    u.nickname as from_nickname
FROM notifications n
JOIN users u ON n.from_id = u.user_id
WHERE n.receiver_id = ? AND n.is_seen = 0
ORDER BY n.created_at DESC
`

type GetUnseenNotificationsWithUserDetailsRow struct {
	NotifID       string
	ReceiverID    []byte
	Type          string
	IsSeen        sql.NullBool
	FromID        []byte
	GroupID       []byte
	EventID       []byte
	CreatedAt     sql.NullTime
	FromFirstName string
	FromLastName  string
	FromAvatar    sql.NullString
	FromNickname  sql.NullString
}

func (q *Queries) GetUnseenNotificationsWithUserDetails(ctx context.Context, receiverID []byte) ([]GetUnseenNotificationsWithUserDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUnseenNotificationsWithUserDetails, receiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnseenNotificationsWithUserDetailsRow
	for rows.Next() {
		var i GetUnseenNotificationsWithUserDetailsRow
		if err := rows.Scan(
			&i.NotifID,
			&i.ReceiverID,
			&i.Type,
			&i.IsSeen,
			&i.FromID,
			&i.GroupID,
			&i.EventID,
			&i.CreatedAt,
			&i.FromFirstName,
			&i.FromLastName,
			&i.FromAvatar,
			&i.FromNickname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsAsSeenForUser = `-- name: MarkAllNotificationsAsSeenForUser :exec
UPDATE notifications
SET is_seen = 1
WHERE receiver_id = ? AND is_seen = 0
`

func (q *Queries) MarkAllNotificationsAsSeenForUser(ctx context.Context, receiverID []byte) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsAsSeenForUser, receiverID)
	return err
}

const markNotificationAsSeen = `-- name: MarkNotificationAsSeen :exec
UPDATE notifications
SET is_seen = 1
WHERE notif_id = ?
`

func (q *Queries) MarkNotificationAsSeen(ctx context.Context, notifID string) error {
	_, err := q.db.ExecContext(ctx, markNotificationAsSeen, notifID)
	return err
}
