// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db_notifications

import (
	"context"
	"database/sql"
)

const countUnseenNotifications = `-- name: CountUnseenNotifications :one
SELECT COUNT(*) FROM notifications
WHERE receiver_id = ? AND is_seen = 0
`

func (q *Queries) CountUnseenNotifications(ctx context.Context, receiverID []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnseenNotifications, receiverID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (notif_id, receiver_id, type, from_id, group_id, event_id, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING notif_id, receiver_id, type, is_seen, from_id, group_id, event_id, created_at
`

type CreateNotificationParams struct {
	NotifID    string
	ReceiverID []byte
	Type       string
	FromID     []byte
	GroupID    []byte
	EventID    []byte
	CreatedAt  sql.NullTime
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.NotifID,
		arg.ReceiverID,
		arg.Type,
		arg.FromID,
		arg.GroupID,
		arg.EventID,
		arg.CreatedAt,
	)
	var i Notification
	err := row.Scan(
		&i.NotifID,
		&i.ReceiverID,
		&i.Type,
		&i.IsSeen,
		&i.FromID,
		&i.GroupID,
		&i.EventID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications WHERE notif_id = ?
`

func (q *Queries) DeleteNotification(ctx context.Context, notifID string) error {
	_, err := q.db.ExecContext(ctx, deleteNotification, notifID)
	return err
}

const deleteNotificationsByReceiverId = `-- name: DeleteNotificationsByReceiverId :exec
DELETE FROM notifications WHERE receiver_id = ?
`

func (q *Queries) DeleteNotificationsByReceiverId(ctx context.Context, receiverID []byte) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationsByReceiverId, receiverID)
	return err
}

const getLastMessageNotification = `-- name: GetLastMessageNotification :one
SELECT created_at FROM notifications
WHERE receiver_id = ? AND from_id = ? AND type = 'message'
ORDER BY created_at DESC
LIMIT 1
`

type GetLastMessageNotificationParams struct {
	ReceiverID []byte
	FromID     []byte
}

func (q *Queries) GetLastMessageNotification(ctx context.Context, arg GetLastMessageNotificationParams) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, getLastMessageNotification, arg.ReceiverID, arg.FromID)
	var created_at sql.NullTime
	err := row.Scan(&created_at)
	return created_at, err
}

const getNotificationById = `-- name: GetNotificationById :one
SELECT notif_id, receiver_id, type, is_seen, from_id, group_id, event_id, created_at FROM notifications WHERE notif_id = ? LIMIT 1
`

func (q *Queries) GetNotificationById(ctx context.Context, notifID string) (Notification, error) {
	row := q.db.QueryRowContext(ctx, getNotificationById, notifID)
	var i Notification
	err := row.Scan(
		&i.NotifID,
		&i.ReceiverID,
		&i.Type,
		&i.IsSeen,
		&i.FromID,
		&i.GroupID,
		&i.EventID,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationWithUserDetails = `-- name: GetNotificationWithUserDetails :many
SELECT
    n.notif_id,
    n.receiver_id,
    n.type,
    n.is_seen,
    n.from_id,
    n.group_id,
    n.event_id,
    n.created_at,
    u.first_name as from_first_name,
    u.last_name as from_last_name,
    u.avatar as from_avatar,
    u.nickname as from_nickname
FROM notifications n
JOIN users u ON n.from_id = u.user_id
WHERE n.receiver_id = ?
ORDER BY n.created_at DESC
`

type GetNotificationWithUserDetailsRow struct {
	NotifID       string
	ReceiverID    []byte
	Type          string
	IsSeen        sql.NullBool
	FromID        []byte
	GroupID       []byte
	EventID       []byte
	CreatedAt     sql.NullTime
	FromFirstName string
	FromLastName  string
	FromAvatar    sql.NullString
	FromNickname  sql.NullString
}

func (q *Queries) GetNotificationWithUserDetails(ctx context.Context, receiverID []byte) ([]GetNotificationWithUserDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationWithUserDetails, receiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNotificationWithUserDetailsRow
	for rows.Next() {
		var i GetNotificationWithUserDetailsRow
		if err := rows.Scan(
			&i.NotifID,
			&i.ReceiverID,
			&i.Type,
			&i.IsSeen,
			&i.FromID,
			&i.GroupID,
			&i.EventID,
			&i.CreatedAt,
			&i.FromFirstName,
			&i.FromLastName,
			&i.FromAvatar,
			&i.FromNickname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationsByReceiverId = `-- name: GetNotificationsByReceiverId :many
SELECT notif_id, receiver_id, type, is_seen, from_id, group_id, event_id, created_at FROM notifications
WHERE receiver_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetNotificationsByReceiverId(ctx context.Context, receiverID []byte) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationsByReceiverId, receiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.NotifID,
			&i.ReceiverID,
			&i.Type,
			&i.IsSeen,
			&i.FromID,
			&i.GroupID,
			&i.EventID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationsByType = `-- name: GetNotificationsByType :many
SELECT notif_id, receiver_id, type, is_seen, from_id, group_id, event_id, created_at FROM notifications
WHERE receiver_id = ? AND type = ?
ORDER BY created_at DESC
`

type GetNotificationsByTypeParams struct {
	ReceiverID []byte
	Type       string
}

func (q *Queries) GetNotificationsByType(ctx context.Context, arg GetNotificationsByTypeParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationsByType, arg.ReceiverID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.NotifID,
			&i.ReceiverID,
			&i.Type,
			&i.IsSeen,
			&i.FromID,
			&i.GroupID,
			&i.EventID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnseenNotificationsByReceiverId = `-- name: GetUnseenNotificationsByReceiverId :many
SELECT notif_id, receiver_id, type, is_seen, from_id, group_id, event_id, created_at FROM notifications
WHERE receiver_id = ? AND is_seen = 0
ORDER BY created_at DESC
`

func (q *Queries) GetUnseenNotificationsByReceiverId(ctx context.Context, receiverID []byte) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getUnseenNotificationsByReceiverId, receiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.NotifID,
			&i.ReceiverID,
			&i.Type,
			&i.IsSeen,
			&i.FromID,
			&i.GroupID,
			&i.EventID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnseenNotificationsWithUserDetails = `-- name: GetUnseenNotificationsWithUserDetails :many
SELECT
    n.notif_id,
    n.receiver_id,
    n.type,
    n.is_seen,
    n.from_id,
    n.group_id,
    n.event_id,
    n.created_at,
    u.first_name as from_first_name,
    u.last_name as from_last_name,
    u.avatar as from_avatar,
    u.nickname as from_nickname
FROM notifications n
JOIN users u ON n.from_id = u.user_id
WHERE n.receiver_id = ? AND n.is_seen = 0
ORDER BY n.created_at DESC
`

type GetUnseenNotificationsWithUserDetailsRow struct {
	NotifID       string
	ReceiverID    []byte
	Type          string
	IsSeen        sql.NullBool
	FromID        []byte
	GroupID       []byte
	EventID       []byte
	CreatedAt     sql.NullTime
	FromFirstName string
	FromLastName  string
	FromAvatar    sql.NullString
	FromNickname  sql.NullString
}

func (q *Queries) GetUnseenNotificationsWithUserDetails(ctx context.Context, receiverID []byte) ([]GetUnseenNotificationsWithUserDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUnseenNotificationsWithUserDetails, receiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnseenNotificationsWithUserDetailsRow
	for rows.Next() {
		var i GetUnseenNotificationsWithUserDetailsRow
		if err := rows.Scan(
			&i.NotifID,
			&i.ReceiverID,
			&i.Type,
			&i.IsSeen,
			&i.FromID,
			&i.GroupID,
			&i.EventID,
			&i.CreatedAt,
			&i.FromFirstName,
			&i.FromLastName,
			&i.FromAvatar,
			&i.FromNickname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsAsSeenForUser = `-- name: MarkAllNotificationsAsSeenForUser :exec
UPDATE notifications
SET is_seen = 1
WHERE receiver_id = ? AND is_seen = 0
`

func (q *Queries) MarkAllNotificationsAsSeenForUser(ctx context.Context, receiverID []byte) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsAsSeenForUser, receiverID)
	return err
}

const markNotificationAsSeen = `-- name: MarkNotificationAsSeen :exec
UPDATE notifications
SET is_seen = 1
WHERE notif_id = ?
`

func (q *Queries) MarkNotificationAsSeen(ctx context.Context, notifID string) error {
	_, err := q.db.ExecContext(ctx, markNotificationAsSeen, notifID)
	return err
}
